/**
 * Schema generation script for Phase 3.
 * Generates:
 * - defaults.generated.ts (createEmptyArticle function)
 * - fieldRegistry.generated.ts (base field entries)
 *
 * Run with: npm run generate:schema
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import {
  substanceArticleSchema,
} from "../../src/schema/substance.schema";
import {
  extractFieldPaths,
  FIELD_REGISTRY_SECTION_ORDER,
  generateArticleDefaults,
  inferFieldRegistrySection,
  type FieldRegistrySection,
  type GeneratedFieldMeta,
} from "./schemaGenerationPolicy";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.join(__dirname, "../../src/data/schema");

/**
 * Generate the createEmptyArticle function as TypeScript code
 */
function generateDefaultsFile(): string {
  const defaults = generateArticleDefaults(substanceArticleSchema);
  const json = JSON.stringify(defaults, null, 2);

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 */

import type { SubstanceArticle } from "../../schema";

/**
 * Create an empty SubstanceArticle with default values derived from the Zod schema.
 */
export function createEmptyArticle(): SubstanceArticle {
  return ${json.replace(/"([^"]+)":/g, "$1:")};
}
`;
}

// ============================================================================
// Field Registry Generation
// ============================================================================

function formatGeneratedFieldEntry(field: GeneratedFieldMeta): string {
  const defaultStr =
    field.default === null
      ? "null"
      : field.default === ""
        ? '""'
        : JSON.stringify(field.default);

  return `  "${field.path}": {
    path: "${field.path}",
    type: "${field.type}",
    default: ${defaultStr},
    isNullable: ${field.isNullable},
  }`;
}

function generateFieldRegistryShardFile(section: FieldRegistrySection, fields: GeneratedFieldMeta[]): string {
  const entries = fields.map(formatGeneratedFieldEntry).join(",\n");

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the ${section} section.
 */

export const ${section}GeneratedFieldRegistry = {
${entries}
};
`;
}

/**
 * Generate the field registry file as TypeScript code
 */
function generateFieldRegistryFile(): string {
  const fields = extractFieldPaths(substanceArticleSchema);
  const sectionImports = FIELD_REGISTRY_SECTION_ORDER.filter((section) =>
    fields.some((field) => inferFieldRegistrySection(field.path) === section),
  );

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * This barrel composes generated field-registry shards by domain.
 * Manual overrides (labels, sections, transformers) are defined in fieldOverrides.ts
 */

${sectionImports
  .map(
    (section) =>
      `import { ${section}GeneratedFieldRegistry } from "./fieldRegistry.generated/${section}";`,
  )
  .join("\n")}

export interface GeneratedFieldMeta {
  path: string;
  type: string;
  default: unknown;
  isNullable: boolean;
}

export const GENERATED_FIELD_REGISTRY: Record<string, GeneratedFieldMeta> = {
${sectionImports.map((section) => `  ...${section}GeneratedFieldRegistry,`).join("\n")}
};

/**
 * List of all field paths in the schema
 */
export const FIELD_PATHS = Object.keys(GENERATED_FIELD_REGISTRY);

export type FieldPath = (typeof FIELD_PATHS)[number];
`;
}

// ============================================================================
// Main
// ============================================================================

function main() {
  console.log("Generating schema utilities...\n");

  // Generate defaults file
  const defaultsContent = generateDefaultsFile();
  const defaultsPath = path.join(OUTPUT_DIR, "defaults.generated.ts");
  fs.writeFileSync(defaultsPath, defaultsContent, "utf-8");
  console.log(`✓ Generated: ${path.relative(process.cwd(), defaultsPath)}`);

  // Generate field registry file
  const fields = extractFieldPaths(substanceArticleSchema);
  const registryShardDir = path.join(OUTPUT_DIR, "fieldRegistry.generated");
  fs.rmSync(registryShardDir, { recursive: true, force: true });
  fs.mkdirSync(registryShardDir, { recursive: true });

  for (const section of FIELD_REGISTRY_SECTION_ORDER) {
    const sectionFields = fields.filter((field) => inferFieldRegistrySection(field.path) === section);
    if (sectionFields.length === 0) {
      continue;
    }

    const shardContent = generateFieldRegistryShardFile(section, sectionFields);
    const shardPath = path.join(registryShardDir, `${section}.ts`);
    fs.writeFileSync(shardPath, shardContent, "utf-8");
  }

  const registryContent = generateFieldRegistryFile();
  const registryPath = path.join(OUTPUT_DIR, "fieldRegistry.generated.ts");
  fs.writeFileSync(registryPath, registryContent, "utf-8");
  console.log(`✓ Generated: ${path.relative(process.cwd(), registryPath)}`);
  console.log(`✓ Generated shards: ${path.relative(process.cwd(), registryShardDir)}`);

  // Count fields
  console.log(`\n📊 Generated ${fields.length} field entries`);

  console.log("\nDone! Now update fieldRegistry.ts to use generated + overrides.");
}

main();
