/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the citations section.
 */

export const citationsGeneratedFieldRegistry = {
  "references": {
    path: "references",
    type: "reference",
    default: [],
    isNullable: false,
  },
  "source_citations": {
    path: "source_citations",
    type: "citation",
    default: undefined,
    isNullable: false,
  },
  "citations": {
    path: "citations",
    type: "citation",
    default: [],
    isNullable: false,
  }
};
