/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the classification section.
 */

export const classificationGeneratedFieldRegistry = {
  "classification.psychoactive_class": {
    path: "classification.psychoactive_class",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "classification.chemical_class": {
    path: "classification.chemical_class",
    type: "tagArray",
    default: [],
    isNullable: false,
  }
};
