/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the dosage section.
 */

export const dosageGeneratedFieldRegistry = {
  "dosage.routes[].route": {
    path: "dosage.routes[].route",
    type: "text",
    default: "",
    isNullable: false,
  },
  "dosage.routes[].bioavailability": {
    path: "dosage.routes[].bioavailability",
    type: "text",
    default: "",
    isNullable: false,
  },
  "dosage.routes[].bioavailability_notes": {
    path: "dosage.routes[].bioavailability_notes",
    type: "text",
    default: "",
    isNullable: false,
  },
  "dosage.routes[].dose_ranges.threshold": {
    path: "dosage.routes[].dose_ranges.threshold",
    type: "dose",
    default: null,
    isNullable: false,
  },
  "dosage.routes[].dose_ranges.light": {
    path: "dosage.routes[].dose_ranges.light",
    type: "dose",
    default: null,
    isNullable: false,
  },
  "dosage.routes[].dose_ranges.moderate": {
    path: "dosage.routes[].dose_ranges.moderate",
    type: "dose",
    default: null,
    isNullable: false,
  },
  "dosage.routes[].dose_ranges.strong": {
    path: "dosage.routes[].dose_ranges.strong",
    type: "dose",
    default: null,
    isNullable: false,
  },
  "dosage.routes[].dose_ranges.heavy": {
    path: "dosage.routes[].dose_ranges.heavy",
    type: "dose",
    default: null,
    isNullable: false,
  },
  "dosage.routes[].notes": {
    path: "dosage.routes[].notes",
    type: "text",
    default: "",
    isNullable: false,
  },
  "dosage.routes[].reference_ids": {
    path: "dosage.routes[].reference_ids",
    type: "array",
    default: [],
    isNullable: false,
  },
  "dosage.plateau_dosing": {
    path: "dosage.plateau_dosing",
    type: "object",
    default: null,
    isNullable: true,
  }
};
