/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the duration section.
 */

export const durationGeneratedFieldRegistry = {
  "duration.routes[].route": {
    path: "duration.routes[].route",
    type: "text",
    default: "",
    isNullable: false,
  },
  "duration.routes[].half_life": {
    path: "duration.routes[].half_life",
    type: "text",
    default: "",
    isNullable: false,
  },
  "duration.routes[].half_life_notes": {
    path: "duration.routes[].half_life_notes",
    type: "text",
    default: "",
    isNullable: false,
  },
  "duration.routes[].stages.onset": {
    path: "duration.routes[].stages.onset",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].stages.come_up": {
    path: "duration.routes[].stages.come_up",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].stages.peak": {
    path: "duration.routes[].stages.peak",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].stages.offset": {
    path: "duration.routes[].stages.offset",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].stages.after_effects": {
    path: "duration.routes[].stages.after_effects",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].stages.total_duration": {
    path: "duration.routes[].stages.total_duration",
    type: "duration",
    default: null,
    isNullable: false,
  },
  "duration.routes[].reference_ids": {
    path: "duration.routes[].reference_ids",
    type: "array",
    default: [],
    isNullable: false,
  }
};
