/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the identification section.
 */

export const identificationGeneratedFieldRegistry = {
  "identification.common_name": {
    path: "identification.common_name",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.substitutive_name": {
    path: "identification.substitutive_name",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.iupac_name": {
    path: "identification.iupac_name",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.alternative_names": {
    path: "identification.alternative_names",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "identification.smiles": {
    path: "identification.smiles",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.inchi_key": {
    path: "identification.inchi_key",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.cas_number": {
    path: "identification.cas_number",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.molecular_formula": {
    path: "identification.molecular_formula",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.molecular_weight": {
    path: "identification.molecular_weight",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.skeletal_structure_image": {
    path: "identification.skeletal_structure_image",
    type: "text",
    default: "",
    isNullable: false,
  },
  "identification.botanical_name": {
    path: "identification.botanical_name",
    type: "text",
    default: "",
    isNullable: false,
  },
  "reagent_testing": {
    path: "reagent_testing",
    type: "object",
    default: {},
    isNullable: false,
  }
};
