/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the interactions section.
 */

export const interactionsGeneratedFieldRegistry = {
  "interactions.dangerous": {
    path: "interactions.dangerous",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "interactions.unsafe": {
    path: "interactions.unsafe",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "interactions.caution": {
    path: "interactions.caution",
    type: "tagArray",
    default: [],
    isNullable: false,
  }
};
