/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the meta section.
 */

export const metaGeneratedFieldRegistry = {
  "id": {
    path: "id",
    type: "number",
    default: null,
    isNullable: true,
  },
  "title": {
    path: "title",
    type: "text",
    default: "",
    isNullable: false,
  },
  "priority": {
    path: "priority",
    type: "text",
    default: "normal",
    isNullable: false,
  },
  "index_categories": {
    path: "index_categories",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "summary": {
    path: "summary",
    type: "text",
    default: "",
    isNullable: false,
  },
  "history_culture": {
    path: "history_culture",
    type: "object",
    default: null,
    isNullable: true,
  },
  "legality.international": {
    path: "legality.international",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "legality.countries": {
    path: "legality.countries",
    type: "object",
    default: {},
    isNullable: false,
  },
  "legality.usStates": {
    path: "legality.usStates",
    type: "object",
    default: {},
    isNullable: false,
  },
  "legality.usStatesNote": {
    path: "legality.usStatesNote",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "editorial_review.status": {
    path: "editorial_review.status",
    type: "text",
    default: "needed",
    isNullable: false,
  },
  "editorial_review.notes": {
    path: "editorial_review.notes",
    type: "text",
    default: "",
    isNullable: false,
  },
  "editorial_review.reviewed_by": {
    path: "editorial_review.reviewed_by",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "editorial_review.reviewed_at": {
    path: "editorial_review.reviewed_at",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "editorial_review.flags": {
    path: "editorial_review.flags",
    type: "object",
    default: [],
    isNullable: false,
  },
  "section_gaps.family": {
    path: "section_gaps.family",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "section_gaps.neighbours": {
    path: "section_gaps.neighbours",
    type: "object",
    default: [],
    isNullable: false,
  },
  "section_gaps.reason": {
    path: "section_gaps.reason",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "section_gaps.sections": {
    path: "section_gaps.sections",
    type: "object",
    default: {},
    isNullable: false,
  }
};
