/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the pharmacology section.
 */

export const pharmacologyGeneratedFieldRegistry = {
  "pharmacology.pharmacodynamics": {
    path: "pharmacology.pharmacodynamics",
    type: "text",
    default: "",
    isNullable: false,
  },
  "pharmacology.summary": {
    path: "pharmacology.summary",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "pharmacology.binding_sites": {
    path: "pharmacology.binding_sites",
    type: "object",
    default: [],
    isNullable: false,
  },
  "pharmacology.pharmacokinetics": {
    path: "pharmacology.pharmacokinetics",
    type: "text",
    default: "",
    isNullable: false,
  },
  "pharmacology.metabolites": {
    path: "pharmacology.metabolites",
    type: "tagArray",
    default: [],
    isNullable: false,
  },
  "pharmacology.protein_binding": {
    path: "pharmacology.protein_binding",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "pharmacology.volume_of_distribution": {
    path: "pharmacology.volume_of_distribution",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "pharmacology.route_bioavailability": {
    path: "pharmacology.route_bioavailability",
    type: "object",
    default: {},
    isNullable: false,
  },
  "pharmacology.route_half_life": {
    path: "pharmacology.route_half_life",
    type: "object",
    default: {},
    isNullable: false,
  },
  "pharmacology.route_half_life_notes": {
    path: "pharmacology.route_half_life_notes",
    type: "object",
    default: {},
    isNullable: false,
  },
  "pharmacology.route_bioavailability_notes": {
    path: "pharmacology.route_bioavailability_notes",
    type: "object",
    default: {},
    isNullable: false,
  },
  "pharmacology.bioavailability_notes": {
    path: "pharmacology.bioavailability_notes",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "pharmacology.half_life": {
    path: "pharmacology.half_life",
    type: "text",
    default: undefined,
    isNullable: false,
  }
};
