/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the subjective_effects section.
 */

export const subjective_effectsGeneratedFieldRegistry = {
  "subjective_effects.notes.overview": {
    path: "subjective_effects.notes.overview",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.notes.sensory": {
    path: "subjective_effects.notes.sensory",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.notes.cognitive": {
    path: "subjective_effects.notes.cognitive",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.notes.physical": {
    path: "subjective_effects.notes.physical",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.visual.note": {
    path: "subjective_effects.sensory.visual.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.visual.subcategories": {
    path: "subjective_effects.sensory.visual.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.sensory.auditory.note": {
    path: "subjective_effects.sensory.auditory.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.auditory.subcategories": {
    path: "subjective_effects.sensory.auditory.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.sensory.tactile.note": {
    path: "subjective_effects.sensory.tactile.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.tactile.subcategories": {
    path: "subjective_effects.sensory.tactile.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.sensory.olfactory.note": {
    path: "subjective_effects.sensory.olfactory.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.olfactory.subcategories": {
    path: "subjective_effects.sensory.olfactory.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.sensory.gustatory.note": {
    path: "subjective_effects.sensory.gustatory.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.gustatory.subcategories": {
    path: "subjective_effects.sensory.gustatory.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.sensory.multisensory.note": {
    path: "subjective_effects.sensory.multisensory.note",
    type: "text",
    default: "",
    isNullable: false,
  },
  "subjective_effects.sensory.multisensory.subcategories": {
    path: "subjective_effects.sensory.multisensory.subcategories",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.cognitive": {
    path: "subjective_effects.cognitive",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.physical": {
    path: "subjective_effects.physical",
    type: "object",
    default: {},
    isNullable: false,
  },
  "subjective_effects.progressive_stages": {
    path: "subjective_effects.progressive_stages",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "subjective_effects.attribution": {
    path: "subjective_effects.attribution",
    type: "object",
    default: null,
    isNullable: true,
  },
  "subjective_effects.is_stub": {
    path: "subjective_effects.is_stub",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "subjective_effects.source_overview": {
    path: "subjective_effects.source_overview",
    type: "text",
    default: undefined,
    isNullable: false,
  },
  "comparisons": {
    path: "comparisons",
    type: "object",
    default: [],
    isNullable: false,
  }
};
