/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * Generated field registry shard for the tolerance section.
 */

export const toleranceGeneratedFieldRegistry = {
  "tolerance.full_tolerance": {
    path: "tolerance.full_tolerance",
    type: "text",
    default: "",
    isNullable: false,
  },
  "tolerance.half_tolerance": {
    path: "tolerance.half_tolerance",
    type: "text",
    default: "",
    isNullable: false,
  },
  "tolerance.baseline_tolerance": {
    path: "tolerance.baseline_tolerance",
    type: "text",
    default: "",
    isNullable: false,
  },
  "tolerance.cross_tolerance": {
    path: "tolerance.cross_tolerance",
    type: "tagArray",
    default: [],
    isNullable: false,
  }
};
