// Auto-generated source favicon configuration
// Maps URL patterns to favicon files
// Generated by scripts/data/generate-further-reading-favicons.mjs

interface SourceConfig { id: string;
patterns: string[];
urlPatterns?: string[];
favicon: string; }

export const sourceConfigs: SourceConfig[] = [
  {
    id: "psychonautwiki",
    patterns: ["psychonautwiki.org","psychonautwiki.net","psychonautwiki.rip"],
    favicon: "/favicons/psychonautwiki.png",
  },
  {
    id: "erowid",
    patterns: ["erowid.org"],
    favicon: "/favicons/erowid.png",
  },
  {
    id: "tripsit",
    patterns: ["tripsit.me"],
    favicon: "/favicons/tripsit.png",
  },
  {
    id: "wikipedia",
    patterns: ["wikipedia.org","wikimedia.org"],
    favicon: "/favicons/wikipedia.png",
  },
  {
    id: "pubmed",
    patterns: ["pubmed.ncbi.nlm.nih.gov","ncbi.nlm.nih.gov","nih.gov","pmc.ncbi.nlm.nih.gov"],
    favicon: "/favicons/pubmed.png",
  },
  {
    id: "bluelight",
    patterns: ["bluelight.org"],
    favicon: "/favicons/bluelight.png",
  },
  {
    id: "reddit",
    patterns: ["reddit.com"],
    favicon: "/favicons/reddit.png",
  },
  {
    id: "pubchem",
    patterns: ["pubchem.ncbi.nlm.nih.gov"],
    favicon: "/favicons/pubchem.png",
  },
  {
    id: "drugbank",
    patterns: ["drugbank.com","go.drugbank.com"],
    favicon: "/favicons/drugbank.png",
  },
  {
    id: "isomerdesign",
    patterns: ["isomerdesign.com","tihkal.info"],
    favicon: "/favicons/isomerdesign.png",
  },
  {
    id: "thedrugclassroom",
    patterns: ["thedrugclassroom.com"],
    favicon: "/favicons/thedrugclassroom.png",
  },
  {
    id: "drugusersbible",
    patterns: ["drugusersbible.org","drugusersbible.com"],
    urlPatterns: ["the-drug-users-bible"],
    favicon: "/favicons/drugusersbible.png",
  },
  {
    id: "dancesafe",
    patterns: ["dancesafe.org"],
    favicon: "/favicons/dancesafe.png",
  },
  {
    id: "drugs-forum",
    patterns: ["drugs-forum.com"],
    favicon: "/favicons/drugs-forum.png",
  },
  {
    id: "disregardeverythingisay",
    patterns: ["disregardeverythingisay.com"],
    favicon: "/favicons/disregardeverythingisay.png",
  },
  {
    id: "analyticalsciencejournals-onlinelibrary-wiley-com",
    patterns: ["analyticalsciencejournals.onlinelibrary.wiley.com"],
    favicon: "/favicons/analyticalsciencejournals-onlinelibrary-wiley-com.png",
  },
  {
    id: "assets-publishing-service-gov-uk",
    patterns: ["assets.publishing.service.gov.uk"],
    favicon: "/favicons/assets-publishing-service-gov-uk.png",
  },
  {
    id: "bpspubs-onlinelibrary-wiley-com",
    patterns: ["bpspubs.onlinelibrary.wiley.com"],
    favicon: "/favicons/bpspubs-onlinelibrary-wiley-com.png",
  },
  {
    id: "psychopharmacologyinstitute-com",
    patterns: ["psychopharmacologyinstitute.com"],
    favicon: "/favicons/psychopharmacologyinstitute-com.png",
  },
  {
    id: "substancemisuseresources-co-uk",
    patterns: ["substancemisuseresources.co.uk"],
    favicon: "/favicons/substancemisuseresources-co-uk.png",
  },
  {
    id: "farmaci-agenziafarmaco-gov-it",
    patterns: ["farmaci.agenziafarmaco.gov.it"],
    favicon: "/favicons/farmaci-agenziafarmaco-gov-it.png",
  },
  {
    id: "wires-onlinelibrary-wiley-com",
    patterns: ["wires.onlinelibrary.wiley.com"],
    favicon: "/favicons/wires-onlinelibrary-wiley-com.png",
  },
  {
    id: "drugintelligencebulletin-com",
    patterns: ["drugintelligencebulletin.com"],
    favicon: "/favicons/drugintelligencebulletin-com.png",
  },
  {
    id: "timesofindia-indiatimes-com",
    patterns: ["timesofindia.indiatimes.com"],
    favicon: "/favicons/timesofindia-indiatimes-com.png",
  },
  {
    id: "molpharm-aspetjournals-org",
    patterns: ["molpharm.aspetjournals.org"],
    favicon: "/favicons/molpharm-aspetjournals-org.png",
  },
  {
    id: "ourfuturesinstitute-org-au",
    patterns: ["ourfuturesinstitute.org.au"],
    favicon: "/favicons/ourfuturesinstitute-org-au.png",
  },
  {
    id: "pharmrev-aspetjournals-org",
    patterns: ["pharmrev.aspetjournals.org"],
    favicon: "/favicons/pharmrev-aspetjournals-org.png",
  },
  {
    id: "supplements-selfdecode-com",
    patterns: ["supplements.selfdecode.com"],
    favicon: "/favicons/supplements-selfdecode-com.png",
  },
  {
    id: "psychedelicsociety-org-uk",
    patterns: ["psychedelicsociety.org.uk"],
    favicon: "/favicons/psychedelicsociety-org-uk.png",
  },
  {
    id: "publichealthscotland-scot",
    patterns: ["publichealthscotland.scot"],
    favicon: "/favicons/publichealthscotland-scot.png",
  },
  {
    id: "researchonline-ljmu-ac-uk",
    patterns: ["researchonline.ljmu.ac.uk"],
    favicon: "/favicons/researchonline-ljmu-ac-uk.png",
  },
  {
    id: "reallifepharmacology-com",
    patterns: ["reallifepharmacology.com"],
    favicon: "/favicons/reallifepharmacology-com.png",
  },
  {
    id: "chemical-collective-com",
    patterns: ["chemical-collective.com"],
    favicon: "/favicons/chemical-collective-com.png",
  },
  {
    id: "jissn-biomedcentral-com",
    patterns: ["jissn.biomedcentral.com"],
    favicon: "/favicons/jissn-biomedcentral-com.png",
  },
  {
    id: "jmsma-scholasticahq-com",
    patterns: ["jmsma.scholasticahq.com"],
    favicon: "/favicons/jmsma-scholasticahq-com.png",
  },
  {
    id: "onlinelibrary-wiley-com",
    patterns: ["onlinelibrary.wiley.com"],
    favicon: "/favicons/onlinelibrary-wiley-com.png",
  },
  {
    id: "theresearchchemslab-com",
    patterns: ["theresearchchemslab.com"],
    favicon: "/favicons/theresearchchemslab-com.png",
  },
  {
    id: "tripsitter-substack-com",
    patterns: ["tripsitter.substack.com"],
    favicon: "/favicons/tripsitter-substack-com.png",
  },
  {
    id: "worldwide-espacenet-com",
    patterns: ["worldwide.espacenet.com"],
    favicon: "/favicons/worldwide-espacenet-com.png",
  },
  {
    id: "deadiversion-usdoj-gov",
    patterns: ["deadiversion.usdoj.gov"],
    favicon: "/favicons/deadiversion-usdoj-gov.png",
  },
  {
    id: "emedicine-medscape-com",
    patterns: ["emedicine.medscape.com"],
    favicon: "/favicons/emedicine-medscape-com.png",
  },
  {
    id: "jpet-aspetjournals-org",
    patterns: ["jpet.aspetjournals.org"],
    favicon: "/favicons/jpet-aspetjournals-org.png",
  },
  {
    id: "nervewing-blogspot-com",
    patterns: ["nervewing.blogspot.com"],
    favicon: "/favicons/nervewing-blogspot-com.png",
  },
  {
    id: "reference-medscape-com",
    patterns: ["reference.medscape.com"],
    favicon: "/favicons/reference-medscape-com.png",
  },
  {
    id: "therecoveryvillage-com",
    patterns: ["therecoveryvillage.com"],
    favicon: "/favicons/therecoveryvillage-com.png",
  },
  {
    id: "ndarc-med-unsw-edu-au",
    patterns: ["ndarc.med.unsw.edu.au"],
    favicon: "/favicons/ndarc-med-unsw-edu-au.png",
  },
  {
    id: "cognitiveliberty-org",
    patterns: ["cognitiveliberty.org"],
    favicon: "/favicons/cognitiveliberty-org.png",
  },
  {
    id: "countyourculture-com",
    patterns: ["countyourculture.com"],
    favicon: "/favicons/countyourculture-com.png",
  },
  {
    id: "dig-pharmacy-uic-edu",
    patterns: ["dig.pharmacy.uic.edu"],
    favicon: "/favicons/dig-pharmacy-uic-edu.png",
  },
  {
    id: "drugs-selfdecode-com",
    patterns: ["drugs.selfdecode.com"],
    favicon: "/favicons/drugs-selfdecode-com.png",
  },
  {
    id: "e-sciencecentral-org",
    patterns: ["e-sciencecentral.org"],
    favicon: "/favicons/e-sciencecentral-org.png",
  },
  {
    id: "globaldrugsurvey-com",
    patterns: ["globaldrugsurvey.com"],
    favicon: "/favicons/globaldrugsurvey-com.png",
  },
  {
    id: "journals-sagepub-com",
    patterns: ["journals.sagepub.com"],
    favicon: "/favicons/journals-sagepub-com.png",
  },
  {
    id: "medicalnewstoday-com",
    patterns: ["medicalnewstoday.com"],
    favicon: "/favicons/medicalnewstoday-com.png",
  },
  {
    id: "medwinpublishers-com",
    patterns: ["medwinpublishers.com"],
    favicon: "/favicons/medwinpublishers-com.png",
  },
  {
    id: "nootropicsexpert-com",
    patterns: ["nootropicsexpert.com"],
    favicon: "/favicons/nootropicsexpert-com.png",
  },
  {
    id: "psychiatryonline-org",
    patterns: ["psychiatryonline.org"],
    favicon: "/favicons/psychiatryonline-org.png",
  },
  {
    id: "spiritpharmacist-com",
    patterns: ["spiritpharmacist.com"],
    favicon: "/favicons/spiritpharmacist-com.png",
  },
  {
    id: "addictioncenter-com",
    patterns: ["addictioncenter.com"],
    favicon: "/favicons/addictioncenter-com.png",
  },
  {
    id: "discovery-ucl-ac-uk",
    patterns: ["discovery.ucl.ac.uk"],
    favicon: "/favicons/discovery-ucl-ac-uk.png",
  },
  {
    id: "federalregister-gov",
    patterns: ["federalregister.gov"],
    favicon: "/favicons/federalregister-gov.png",
  },
  {
    id: "lpi-oregonstate-edu",
    patterns: ["lpi.oregonstate.edu"],
    favicon: "/favicons/lpi-oregonstate-edu.png",
  },
  {
    id: "mind-foundation-org",
    patterns: ["mind-foundation.org"],
    favicon: "/favicons/mind-foundation-org.png",
  },
  {
    id: "nootropicsdepot-com",
    patterns: ["nootropicsdepot.com"],
    favicon: "/favicons/nootropicsdepot-com.png",
  },
  {
    id: "substancesearch-org",
    patterns: ["substancesearch.org"],
    favicon: "/favicons/substancesearch-org.png",
  },
  {
    id: "accessdata-fda-gov",
    patterns: ["accessdata.fda.gov"],
    favicon: "/favicons/accessdata-fda-gov.png",
  },
  {
    id: "antonpottegaard-dk",
    patterns: ["antonpottegaard.dk"],
    favicon: "/favicons/antonpottegaard-dk.png",
  },
  {
    id: "cdn-caymanchem-com",
    patterns: ["cdn.caymanchem.com"],
    favicon: "/favicons/cdn-caymanchem-com.png",
  },
  {
    id: "doubleblindmag-com",
    patterns: ["doubleblindmag.com"],
    favicon: "/favicons/doubleblindmag-com.png",
  },
  {
    id: "drugsandalcohol-ie",
    patterns: ["drugsandalcohol.ie"],
    favicon: "/favicons/drugsandalcohol-ie.png",
  },
  {
    id: "drugscience-org-uk",
    patterns: ["drugscience.org.uk"],
    favicon: "/favicons/drugscience-org-uk.png",
  },
  {
    id: "ecddrepository-org",
    patterns: ["ecddrepository.org"],
    favicon: "/favicons/ecddrepository-org.png",
  },
  {
    id: "health-harvard-edu",
    patterns: ["health.harvard.edu"],
    favicon: "/favicons/health-harvard-edu.png",
  },
  {
    id: "hempgeneration-com",
    patterns: ["hempgeneration.com"],
    favicon: "/favicons/hempgeneration-com.png",
  },
  {
    id: "legislation-gov-uk",
    patterns: ["legislation.gov.uk"],
    favicon: "/favicons/legislation-gov-uk.png",
  },
  {
    id: "medchemexpress-com",
    patterns: ["medchemexpress.com"],
    favicon: "/favicons/medchemexpress-com.png",
  },
  {
    id: "patents-google-com",
    patterns: ["patents.google.com"],
    favicon: "/favicons/patents-google-com.png",
  },
  {
    id: "psychotropical-com",
    patterns: ["psychotropical.com"],
    favicon: "/favicons/psychotropical-com.png",
  },
  {
    id: "emergency-cdc-gov",
    patterns: ["emergency.cdc.gov"],
    favicon: "/favicons/emergency-cdc-gov.png",
  },
  {
    id: "europol-europa-eu",
    patterns: ["europol.europa.eu"],
    favicon: "/favicons/europol-europa-eu.png",
  },
  {
    id: "health-vic-gov-au",
    patterns: ["health.vic.gov.au"],
    favicon: "/favicons/health-vic-gov-au.png",
  },
  {
    id: "journals-plos-org",
    patterns: ["journals.plos.org"],
    favicon: "/favicons/journals-plos-org.png",
  },
  {
    id: "link-springer-com",
    patterns: ["link.springer.com"],
    favicon: "/favicons/link-springer-com.png",
  },
  {
    id: "sciencedirect-com",
    patterns: ["sciencedirect.com"],
    favicon: "/favicons/sciencedirect-com.png",
  },
  {
    id: "search-dedgrl-com",
    patterns: ["search.dedgrl.com"],
    favicon: "/favicons/search-dedgrl-com.png",
  },
  {
    id: "substance-uvic-ca",
    patterns: ["substance.uvic.ca"],
    favicon: "/favicons/substance-uvic-ca.png",
  },
  {
    id: "taylorfrancis-com",
    patterns: ["taylorfrancis.com"],
    favicon: "/favicons/taylorfrancis-com.png",
  },
  {
    id: "vet-us-virbac-com",
    patterns: ["vet-us.virbac.com"],
    favicon: "/favicons/vet-us-virbac-com.png",
  },
  {
    id: "yourinception-com",
    patterns: ["yourinception.com"],
    favicon: "/favicons/yourinception-com.png",
  },
  {
    id: "academic-oup-com",
    patterns: ["academic.oup.com"],
    favicon: "/favicons/academic-oup-com.png",
  },
  {
    id: "alzdiscovery-org",
    patterns: ["alzdiscovery.org"],
    favicon: "/favicons/alzdiscovery-org.png",
  },
  {
    id: "books-google-com",
    patterns: ["books.google.com"],
    favicon: "/favicons/books-google-com.png",
  },
  {
    id: "chemicalbook-com",
    patterns: ["chemicalbook.com"],
    favicon: "/favicons/chemicalbook-com.png",
  },
  {
    id: "dfs-virginia-gov",
    patterns: ["dfs.virginia.gov"],
    favicon: "/favicons/dfs-virginia-gov.png",
  },
  {
    id: "drugfacts-org-uk",
    patterns: ["drugfacts.org.uk"],
    favicon: "/favicons/drugfacts-org-uk.png",
  },
  {
    id: "emcdda-europa-eu",
    patterns: ["emcdda.europa.eu"],
    favicon: "/favicons/emcdda-europa-eu.png",
  },
  {
    id: "headwatersfl-org",
    patterns: ["headwatersfl.org"],
    favicon: "/favicons/headwatersfl-org.png",
  },
  {
    id: "inxight-ncats-io",
    patterns: ["inxight.ncats.io"],
    favicon: "/favicons/inxight-ncats-io.png",
  },
  {
    id: "j-initiative-org",
    patterns: ["j-initiative.org"],
    favicon: "/favicons/j-initiative-org.png",
  },
  {
    id: "journals-lww-com",
    patterns: ["journals.lww.com"],
    favicon: "/favicons/journals-lww-com.png",
  },
  {
    id: "knowyourstuff-nz",
    patterns: ["knowyourstuff.nz"],
    favicon: "/favicons/knowyourstuff-nz.png",
  },
  {
    id: "lgcstandards-com",
    patterns: ["lgcstandards.com"],
    favicon: "/favicons/lgcstandards-com.png",
  },
  {
    id: "psychiatrist-com",
    patterns: ["psychiatrist.com"],
    favicon: "/favicons/psychiatrist-com.png",
  },
  {
    id: "psychotropics-dk",
    patterns: ["psychotropics.dk"],
    favicon: "/favicons/psychotropics-dk.png",
  },
  {
    id: "researchgate-net",
    patterns: ["researchgate.net"],
    favicon: "/favicons/researchgate-net.png",
  },
  {
    id: "sigmaaldrich-com",
    patterns: ["sigmaaldrich.com"],
    favicon: "/favicons/sigmaaldrich-com.png",
  },
  {
    id: "teamchemists-com",
    patterns: ["teamchemists.com"],
    favicon: "/favicons/teamchemists-com.png",
  },
  {
    id: "uspharmacist-com",
    patterns: ["uspharmacist.com"],
    favicon: "/favicons/uspharmacist-com.png",
  },
  {
    id: "webbook-nist-gov",
    patterns: ["webbook.nist.gov"],
    favicon: "/favicons/webbook-nist-gov.png",
  },
  {
    id: "annemergmed-com",
    patterns: ["annemergmed.com"],
    favicon: "/favicons/annemergmed-com.png",
  },
  {
    id: "braintropic-com",
    patterns: ["braintropic.com"],
    favicon: "/favicons/braintropic-com.png",
  },
  {
    id: "drugs-page-link",
    patterns: ["drugs.page.link"],
    favicon: "/favicons/drugs-page-link.png",
  },
  {
    id: "drugwise-org-uk",
    patterns: ["drugwise.org.uk"],
    favicon: "/favicons/drugwise-org-uk.png",
  },
  {
    id: "frontiersin-org",
    patterns: ["frontiersin.org"],
    favicon: "/favicons/frontiersin-org.png",
  },
  {
    id: "jamanetwork-com",
    patterns: ["jamanetwork.com"],
    favicon: "/favicons/jamanetwork-com.png",
  },
  {
    id: "mayoclinico-org",
    patterns: ["mayoclinico.org"],
    favicon: "/favicons/mayoclinico-org.png",
  },
  {
    id: "medlineplus-gov",
    patterns: ["medlineplus.gov"],
    favicon: "/favicons/medlineplus-gov.png",
  },
  {
    id: "talktofrank-com",
    patterns: ["talktofrank.com"],
    favicon: "/favicons/talktofrank-com.png",
  },
  {
    id: "thelevel-org-nz",
    patterns: ["thelevel.org.nz"],
    favicon: "/favicons/thelevel-org-nz.png",
  },
  {
    id: "thethirdwave-co",
    patterns: ["thethirdwave.co"],
    favicon: "/favicons/thethirdwave-co.png",
  },
  {
    id: "thevespiary-org",
    patterns: ["thevespiary.org"],
    favicon: "/favicons/thevespiary-org.png",
  },
  {
    id: "zeptometrix-com",
    patterns: ["zeptometrix.com"],
    favicon: "/favicons/zeptometrix-com.png",
  },
  {
    id: "britannica-com",
    patterns: ["britannica.com"],
    favicon: "/favicons/britannica-com.png",
  },
  {
    id: "caymanchem-com",
    patterns: ["caymanchem.com"],
    favicon: "/favicons/caymanchem-com.png",
  },
  {
    id: "cerilliant-com",
    patterns: ["cerilliant.com"],
    favicon: "/favicons/cerilliant-com.png",
  },
  {
    id: "chemspider-com",
    patterns: ["chemspider.com"],
    favicon: "/favicons/chemspider-com.png",
  },
  {
    id: "drugs-ncats-io",
    patterns: ["drugs.ncats.io"],
    favicon: "/favicons/drugs-ncats-io.png",
  },
  {
    id: "edoc-unibas-ch",
    patterns: ["edoc.unibas.ch"],
    favicon: "/favicons/edoc-unibas-ch.png",
  },
  {
    id: "euda-europa-eu",
    patterns: ["euda.europa.eu"],
    favicon: "/favicons/euda-europa-eu.png",
  },
  {
    id: "flmodafinil-pl",
    patterns: ["flmodafinil.pl"],
    favicon: "/favicons/flmodafinil-pl.png",
  },
  {
    id: "fpnotebook-com",
    patterns: ["fpnotebook.com"],
    favicon: "/favicons/fpnotebook-com.png",
  },
  {
    id: "healthline-com",
    patterns: ["healthline.com"],
    favicon: "/favicons/healthline-com.png",
  },
  {
    id: "highresnps-com",
    patterns: ["highresnps.com"],
    favicon: "/favicons/highresnps-com.png",
  },
  {
    id: "mayoclinic-org",
    patterns: ["mayoclinic.org"],
    favicon: "/favicons/mayoclinic-org.png",
  },
  {
    id: "projectcbd-org",
    patterns: ["projectcbd.org"],
    favicon: "/favicons/projectcbd-org.png",
  },
  {
    id: "release-org-uk",
    patterns: ["release.org.uk"],
    favicon: "/favicons/release-org-uk.png",
  },
  {
    id: "selfhacked-com",
    patterns: ["selfhacked.com"],
    favicon: "/favicons/selfhacked-com.png",
  },
  {
    id: "trippywiki-com",
    patterns: ["trippywiki.com"],
    favicon: "/favicons/trippywiki-com.png",
  },
  {
    id: "tripreport-net",
    patterns: ["tripreport.net"],
    favicon: "/favicons/tripreport-net.png",
  },
  {
    id: "tripsitter-com",
    patterns: ["tripsitter.com"],
    favicon: "/favicons/tripsitter-com.png",
  },
  {
    id: "anonfiles-com",
    patterns: ["anonfiles.com"],
    favicon: "/favicons/anonfiles-com.png",
  },
  {
    id: "benchchem-com",
    patterns: ["benchchem.com"],
    favicon: "/favicons/benchchem-com.png",
  },
  {
    id: "drugsdata-org",
    patterns: ["drugsdata.org"],
    favicon: "/favicons/drugsdata-org.png",
  },
  {
    id: "europepmc-org",
    patterns: ["europepmc.org"],
    favicon: "/favicons/europepmc-org.png",
  },
  {
    id: "evitachem-com",
    patterns: ["evitachem.com"],
    favicon: "/favicons/evitachem-com.png",
  },
  {
    id: "hi-ground-org",
    patterns: ["hi-ground.org"],
    favicon: "/favicons/hi-ground-org.png",
  },
  {
    id: "jneurosci-org",
    patterns: ["jneurosci.org"],
    favicon: "/favicons/jneurosci-org.png",
  },
  {
    id: "knowdrugs-app",
    patterns: ["knowdrugs.app"],
    favicon: "/favicons/knowdrugs-app.png",
  },
  {
    id: "modafinil-com",
    patterns: ["modafinil.com"],
    favicon: "/favicons/modafinil-com.png",
  },
  {
    id: "modafinil-org",
    patterns: ["modafinil.org"],
    favicon: "/favicons/modafinil-org.png",
  },
  {
    id: "smolecule-com",
    patterns: ["smolecule.com"],
    favicon: "/favicons/smolecule-com.png",
  },
  {
    id: "talkiatry-com",
    patterns: ["talkiatry.com"],
    favicon: "/favicons/talkiatry-com.png",
  },
  {
    id: "anodyne-wiki",
    patterns: ["anodyne.wiki"],
    favicon: "/favicons/anodyne-wiki.png",
  },
  {
    id: "benzo-org-uk",
    patterns: ["benzo.org.uk"],
    favicon: "/favicons/benzo-org-uk.png",
  },
  {
    id: "biosynth-com",
    patterns: ["biosynth.com"],
    favicon: "/favicons/biosynth-com.png",
  },
  {
    id: "bluedark-org",
    patterns: ["bluedark.org"],
    favicon: "/favicons/bluedark-org.png",
  },
  {
    id: "cahma-org-au",
    patterns: ["cahma.org.au"],
    favicon: "/favicons/cahma-org-au.png",
  },
  {
    id: "chacruna-net",
    patterns: ["chacruna.net"],
    favicon: "/favicons/chacruna-net.png",
  },
  {
    id: "epilepsy-com",
    patterns: ["epilepsy.com"],
    favicon: "/favicons/epilepsy-com.png",
  },
  {
    id: "news-sky-com",
    patterns: ["news.sky.com"],
    favicon: "/favicons/news-sky-com.png",
  },
  {
    id: "op-europa-eu",
    patterns: ["op.europa.eu"],
    favicon: "/favicons/op-europa-eu.png",
  },
  {
    id: "pdsp-unc-edu",
    patterns: ["pdsp.unc.edu"],
    favicon: "/favicons/pdsp-unc-edu.png",
  },
  {
    id: "pubs-acs-org",
    patterns: ["pubs.acs.org"],
    favicon: "/favicons/pubs-acs-org.png",
  },
  {
    id: "pubs-rsc-org",
    patterns: ["pubs.rsc.org"],
    favicon: "/favicons/pubs-rsc-org.png",
  },
  {
    id: "rc-community",
    patterns: ["rc.community"],
    favicon: "/favicons/rc-community.png",
  },
  {
    id: "rollsafe-org",
    patterns: ["rollsafe.org"],
    favicon: "/favicons/rollsafe-org.png",
  },
  {
    id: "wada-ama-org",
    patterns: ["wada-ama.org"],
    favicon: "/favicons/wada-ama-org.png",
  },
  {
    id: "zoetisus-com",
    patterns: ["zoetisus.com"],
    favicon: "/favicons/zoetisus-com.png",
  },
  {
    id: "archive-org",
    patterns: ["archive.org"],
    favicon: "/favicons/archive-org.png",
  },
  {
    id: "cdn-who-int",
    patterns: ["cdn.who.int"],
    favicon: "/favicons/cdn-who-int.png",
  },
  {
    id: "examine-com",
    patterns: ["examine.com"],
    favicon: "/favicons/examine-com.png",
  },
  {
    id: "heffter-org",
    patterns: ["heffter.org"],
    favicon: "/favicons/heffter-org.png",
  },
  {
    id: "jellinek-nl",
    patterns: ["jellinek.nl"],
    favicon: "/favicons/jellinek-nl.png",
  },
  {
    id: "medtigo-com",
    patterns: ["medtigo.com"],
    favicon: "/favicons/medtigo-com.png",
  },
  {
    id: "memphis-edu",
    patterns: ["memphis.edu"],
    favicon: "/favicons/memphis-edu.png",
  },
  {
    id: "policija-si",
    patterns: ["policija.si"],
    favicon: "/favicons/policija-si.png",
  },
  {
    id: "purerawz-co",
    patterns: ["purerawz.co"],
    favicon: "/favicons/purerawz-co.png",
  },
  {
    id: "swgdrug-org",
    patterns: ["swgdrug.org"],
    favicon: "/favicons/swgdrug-org.png",
  },
  {
    id: "wedinos-org",
    patterns: ["wedinos.org"],
    favicon: "/favicons/wedinos-org.png",
  },
  {
    id: "wikidoc-org",
    patterns: ["wikidoc.org"],
    favicon: "/favicons/wikidoc-org.png",
  },
  {
    id: "3dchem-com",
    patterns: ["3dchem.com"],
    favicon: "/favicons/3dchem-com.png",
  },
  {
    id: "adf-org-au",
    patterns: ["adf.org.au"],
    favicon: "/favicons/adf-org-au.png",
  },
  {
    id: "buzzrx-com",
    patterns: ["buzzrx.com"],
    favicon: "/favicons/buzzrx-com.png",
  },
  {
    id: "drug-do-se",
    patterns: ["drug-do.se"],
    favicon: "/favicons/drug-do-se.png",
  },
  {
    id: "emcrit-org",
    patterns: ["emcrit.org"],
    favicon: "/favicons/emcrit-org.png",
  },
  {
    id: "glpbio-com",
    patterns: ["glpbio.com"],
    favicon: "/favicons/glpbio-com.png",
  },
  {
    id: "goodrx-com",
    patterns: ["goodrx.com"],
    favicon: "/favicons/goodrx-com.png",
  },
  {
    id: "inchem-org",
    patterns: ["inchem.org"],
    favicon: "/favicons/inchem-org.png",
  },
  {
    id: "nature-com",
    patterns: ["nature.com"],
    favicon: "/favicons/nature-com.png",
  },
  {
    id: "nps-org-au",
    patterns: ["nps.org.au"],
    favicon: "/favicons/nps-org-au.png",
  },
  {
    id: "people-com",
    patterns: ["people.com"],
    favicon: "/favicons/people-com.png",
  },
  {
    id: "poison-org",
    patterns: ["poison.org"],
    favicon: "/favicons/poison-org.png",
  },
  {
    id: "pulsus-com",
    patterns: ["pulsus.com"],
    favicon: "/favicons/pulsus-com.png",
  },
  {
    id: "rxlist-com",
    patterns: ["rxlist.com"],
    favicon: "/favicons/rxlist-com.png",
  },
  {
    id: "tocris-com",
    patterns: ["tocris.com"],
    favicon: "/favicons/tocris-com.png",
  },
  {
    id: "vinmec-com",
    patterns: ["vinmec.com"],
    favicon: "/favicons/vinmec-com.png",
  },
  {
    id: "caam-tech",
    patterns: ["caam.tech"],
    favicon: "/favicons/caam-tech.png",
  },
  {
    id: "canada-ca",
    patterns: ["canada.ca"],
    favicon: "/favicons/canada-ca.png",
  },
  {
    id: "cfsre-org",
    patterns: ["cfsre.org"],
    favicon: "/favicons/cfsre-org.png",
  },
  {
    id: "crew-scot",
    patterns: ["crew.scot"],
    favicon: "/favicons/crew-scot.png",
  },
  {
    id: "d-nb-info",
    patterns: ["d-nb.info"],
    favicon: "/favicons/d-nb-info.png",
  },
  {
    id: "drugs-com",
    patterns: ["drugs.com"],
    favicon: "/favicons/drugs-com.png",
  },
  {
    id: "ijest-org",
    patterns: ["ijest.org"],
    favicon: "/favicons/ijest-org.png",
  },
  {
    id: "loinc-org",
    patterns: ["loinc.org"],
    favicon: "/favicons/loinc-org.png",
  },
  {
    id: "ndews-org",
    patterns: ["ndews.org"],
    favicon: "/favicons/ndews-org.png",
  },
  {
    id: "rnz-co-nz",
    patterns: ["rnz.co.nz"],
    favicon: "/favicons/rnz-co-nz.png",
  },
  {
    id: "unodc-org",
    patterns: ["unodc.org"],
    favicon: "/favicons/unodc-org.png",
  },
  {
    id: "usada-org",
    patterns: ["usada.org"],
    favicon: "/favicons/usada-org.png",
  },
  {
    id: "webmd-com",
    patterns: ["webmd.com"],
    favicon: "/favicons/webmd-com.png",
  },
  {
    id: "acmt-net",
    patterns: ["acmt.net"],
    favicon: "/favicons/acmt-net.png",
  },
  {
    id: "bccsu-ca",
    patterns: ["bccsu.ca"],
    favicon: "/favicons/bccsu-ca.png",
  },
  {
    id: "drugs-ie",
    patterns: ["drugs.ie"],
    favicon: "/favicons/drugs-ie.png",
  },
  {
    id: "incb-org",
    patterns: ["incb.org"],
    favicon: "/favicons/incb-org.png",
  },
  {
    id: "maps-org",
    patterns: ["maps.org"],
    favicon: "/favicons/maps-org.png",
  },
  {
    id: "mdpi-com",
    patterns: ["mdpi.com"],
    favicon: "/favicons/mdpi-com.png",
  },
  {
    id: "mims-com",
    patterns: ["mims.com"],
    favicon: "/favicons/mims-com.png",
  },
  {
    id: "nejm-org",
    patterns: ["nejm.org"],
    favicon: "/favicons/nejm-org.png",
  },
  {
    id: "self-com",
    patterns: ["self.com"],
    favicon: "/favicons/self-com.png",
  },
  {
    id: "vice-com",
    patterns: ["vice.com"],
    favicon: "/favicons/vice-com.png",
  },
  {
    id: "vumc-org",
    patterns: ["vumc.org"],
    favicon: "/favicons/vumc-org.png",
  },
  {
    id: "youtu-be",
    patterns: ["youtu.be"],
    favicon: "/favicons/youtu-be.png",
  },
  {
    id: "cdc-gov",
    patterns: ["cdc.gov"],
    favicon: "/favicons/cdc-gov.png",
  },
  {
    id: "dea-gov",
    patterns: ["dea.gov"],
    favicon: "/favicons/dea-gov.png",
  },
  {
    id: "dhs-gov",
    patterns: ["dhs.gov"],
    favicon: "/favicons/dhs-gov.png",
  },
  {
    id: "doi-org",
    patterns: ["doi.org"],
    favicon: "/favicons/doi-org.png",
  },
  {
    id: "fda-gov",
    patterns: ["fda.gov"],
    favicon: "/favicons/fda-gov.png",
  },
  {
    id: "ofdt-fr",
    patterns: ["ofdt.fr"],
    favicon: "/favicons/ofdt-fr.png",
  },
  {
    id: "pbs-org",
    patterns: ["pbs.org"],
    favicon: "/favicons/pbs-org.png",
  },
  {
    id: "rivm-nl",
    patterns: ["rivm.nl"],
    favicon: "/favicons/rivm-nl.png",
  },
  {
    id: "who-int",
    patterns: ["who.int"],
    favicon: "/favicons/who-int.png",
  },
  {
    id: "gov-uk",
    patterns: ["gov.uk"],
    favicon: "/favicons/gov-uk.png",
  }
];

/**
 * Map display names from quotes files to source IDs.
 * Used to look up favicons for sources extracted from markdown quotes.
 */
export const sourceDisplayNameToId: Record<string, string | null> = {
  "PsychonautWiki": "psychonautwiki",
  "Erowid": "erowid",
  "TripSit Factsheets": "tripsit",
  "TripSit Wiki": "tripsit",
  "Wikipedia": "wikipedia",
  "DrugBank": "drugbank",
  "Isomer Design": "isomerdesign",
  "The Drug Classroom": "thedrugclassroom",
  "Drug Users Bible": "drugusersbible",
  "Disregard Everything I Say": "disregardeverythingisay",
  "SaferParty": null,
  "DanceSafe": "dancesafe",
  "Bluelight": "bluelight",
  "PubMed": "pubmed",
  "Reddit": "reddit",
};

function trimTrailingUrlPunctuation(value: string): string {
  return value.replace(/[\])}.,;:]+$/g, "");
}

function extractLookupUrl(value: string): string | null {
  const trimmed = typeof value === "string" ? value.trim() : "";
  if (!trimmed) return null;

  const candidates = [trimmed];
  const embeddedUrl = trimmed.match(/https?:\/\/[^\s<>"']+/i)?.[0];
  if (embeddedUrl) {
    candidates.unshift(trimTrailingUrlPunctuation(embeddedUrl));
  }

  const doi = trimmed.match(/\bdoi\s*:?\s*(10\.\d{4,9}\/[^\s]+)/i)?.[1]
    ?? trimmed.match(/\b(10\.\d{4,9}\/[^\s]+)/i)?.[1];
  if (doi) {
    candidates.push(`https://doi.org/${trimTrailingUrlPunctuation(doi)}`);
  }

  const pmid = trimmed.match(/\b(?:PMID|PubMed\s+ID)\s*:?\s*(\d{5,})\b/i)?.[1];
  if (pmid) {
    candidates.push(`https://pubmed.ncbi.nlm.nih.gov/${pmid}/`);
  }

  for (const candidate of candidates) {
    try {
      return new URL(candidate).toString();
    } catch {
      // Try the next candidate.
    }
  }

  return null;
}

/**
 * Get favicon path for a citation URL or legacy citation text containing a URL, DOI, or PMID.
 */
export function getFaviconForUrl(url: string): string | null {
  try {
    const lookupUrl = extractLookupUrl(url);
    if (!lookupUrl) return null;

    const parsedUrl = new URL(lookupUrl);
    const hostname = parsedUrl.hostname.toLowerCase();
    const fullUrl = lookupUrl.toLowerCase();

    for (const source of sourceConfigs) {
      if (source.patterns.some((pattern) => hostname.includes(pattern))) {
        return source.favicon;
      }

      if (source.urlPatterns?.some((pattern) => fullUrl.includes(pattern))) {
        return source.favicon;
      }
    }
  } catch {
    // Invalid URL.
  }

  return null;
}

/**
 * Get favicon path for a source display name (from quotes files).
 */
export function getFaviconForSourceName(name: string): string | null {
  const id = sourceDisplayNameToId[name];
  if (!id) return null;
  const config = sourceConfigs.find((source) => source.id === id);
  return config?.favicon ?? null;
}
