import type { IconName } from "@/components/common/Icon";

const EXACT_HEADING_ICONS: Record<string, IconName> = {
  "Discovery and Development": "lucide:flask-conical",
  "Discovery and Synthesis": "lucide:flask-conical",
  "Discovery and Early Research": "lucide:flask-conical",
  "Discovery and Early Development": "lucide:flask-conical",
  "Discovery and Scientific Development": "lucide:flask-conical",
  "Discovery and Early Synthesis": "lucide:flask-conical",
  "Discovery and Isolation": "lucide:flask-conical",
  "Discovery and Medical Development": "lucide:flask-conical",
  "Discovery and Significance": "lucide:flask-conical",
  "Discovery and Emergence": "lucide:flask-conical",
  "Discovery and Initial Research": "lucide:flask-conical",
  "Discovery and Early History": "lucide:flask-conical",
  "Discovery and Commercial Development": "lucide:flask-conical",
  "Discovery and Pharmaceutical Development": "lucide:flask-conical",
  "Discovery and Commercial Introduction": "lucide:flask-conical",
  "Synthesis and Early Research": "lucide:flask-conical",
  "Synthesis and Early Development": "lucide:flask-conical",
  "Synthesis and Isolation": "lucide:flask-conical",
  "Synthesis and Scientific Discovery": "lucide:flask-conical",
  "Synthesis and Commercial Development": "lucide:flask-conical",
  "Synthesis and Medical Development": "lucide:flask-conical",
  "Synthesis": "lucide:flask-conical",
  "Design and Synthesis": "lucide:flask-conical",
  "Chemical Identification and Synthesis": "lucide:flask-conical",
  "Chemical Isolation and Synthesis": "lucide:flask-conical",
  "Western Discovery and Synthesis": "lucide:flask-conical",
  "Scientific Discovery": "lucide:flask-conical",
  "Scientific Discovery and Early Medical Applications": "lucide:flask-conical",
  "Antidepressant Discovery": "lucide:flask-conical",
  "Discovery of Anti-Addiction Properties": "lucide:flask-conical",
  "Discovery of Anticonvulsant Properties": "lucide:flask-conical",
  "Modern Isolation": "lucide:flask-conical",
  "Isolation and Medical Development": "lucide:flask-conical",
  "Origins and Discovery": "lucide:flask-conical",
  "Therapeutic Research": "lucide:microscope",
  "Clinical Research": "lucide:microscope",
  "Pharmaceutical Research": "lucide:microscope",
  "Scientific Research": "lucide:microscope",
  "Scientific Research Applications": "lucide:microscope",
  "Scientific Interest": "lucide:microscope",
  "Scientific Development": "lucide:microscope",
  "Research and Publication": "lucide:microscope",
  "Early Research and Commentary": "lucide:microscope",
  "Early Research and Medical Development": "lucide:microscope",
  "Therapeutic and Cognitive Research": "lucide:microscope",
  "Alcoholism Research": "lucide:microscope",
  "Research into Addiction Treatment Potential": "lucide:microscope",
  "Medical and Psychiatric Research": "lucide:microscope",
  "Intelligence Agency Research": "lucide:microscope",
  "Psychotherapeutic Research": "lucide:microscope",
  "Government Research Programs": "lucide:microscope",
  "Academic Research and the Prohibition Era": "lucide:microscope",
  "Research Renaissance": "lucide:microscope",
  "Modern Research Revival": "lucide:microscope",
  "Contemporary Research": "lucide:microscope",
  "Research and Cultural Expression": "lucide:microscope",
  "Development as a Research Tool": "lucide:microscope",
  "Medical Patent Research": "lucide:microscope",
  "Medical and Military Applications": "lucide:stethoscope",
  "Psychiatric Applications": "lucide:stethoscope",
  "Therapeutic Use": "lucide:stethoscope",
  "Early Medical Use and Research": "lucide:stethoscope",
  "Medical Use and Changing Perceptions": "lucide:stethoscope",
  "Medical Use and Discontinuation": "lucide:stethoscope",
  "Contemporary Medical Use": "lucide:stethoscope",
  "Early Medical Applications": "lucide:stethoscope",
  "Post-War Medical Applications": "lucide:stethoscope",
  "ADHD Treatment": "lucide:stethoscope",
  "Development as Addiction Treatment": "lucide:stethoscope",
  "End-of-Life Applications": "lucide:stethoscope",
  "Use in Medical-Assisted Dying": "lucide:stethoscope",
  "Specialized Applications": "lucide:stethoscope",
  "Medical Decline": "lucide:stethoscope",
  "Development and Approval": "lucide:pill",
  "Pharmaceutical Development": "lucide:pill",
  "Modern Pharmaceutical Development": "lucide:pill",
  "Medical Formulation Development": "lucide:pill",
  "Extended-Release Formulations": "lucide:pill",
  "Modern Formulations": "lucide:pill",
  "Development and Commercialization": "lucide:pill",
  "Development and Medical Approval": "lucide:pill",
  "Development and Initial Research": "lucide:pill",
  "Development and Regulatory Approval": "lucide:pill",
  "Development and Soviet Adoption": "lucide:pill",
  "Development of OxyContin": "lucide:pill",
  "Clinical Approval and Commercialization": "lucide:pill",
  "Influence on Antidepressant Development": "lucide:pill",
  "Commercial and Medical Development": "lucide:pill",
  "Commercial Development and Medical Applications": "lucide:pill",
  "Commercial Development and Medical Adoption": "lucide:pill",
  "Commercialization and Medical Use": "lucide:pill",
  "Medical Adoption and Regulatory Approvals": "lucide:pill",
  "Displacement by Benzodiazepines": "lucide:pill",
  "Commercial History": "lucide:building-2",
  "Commercial Success": "lucide:building-2",
  "Commercial Availability": "lucide:building-2",
  "Commercial Marketing and Recreational Emergence": "lucide:building-2",
  "Commercial History and Supply Disruptions": "lucide:building-2",
  "Market Emergence": "lucide:building-2",
  "Market Withdrawal": "lucide:building-2",
  "Grey Market Availability": "lucide:building-2",
  "United States Market Dominance": "lucide:building-2",
  "Emergence in Consumer Markets": "lucide:building-2",
  "Rediscovery and Commercial Introduction": "lucide:building-2",
  "International Regulatory Response": "lucide:scale",
  "Regulatory Developments": "lucide:scale",
  "Regulatory Status and Documentation": "lucide:scale",
  "Regulatory Approvals": "lucide:scale",
  "Regulatory Changes and Reformulations": "lucide:scale",
  "Regulatory Approval and Commercialization": "lucide:scale",
  "Regulatory Approval and Market Entry": "lucide:scale",
  "United States Regulatory Approval": "lucide:scale",
  "European Market Authorization": "lucide:scale",
  "International Scheduling": "lucide:scale",
  "Historical Regulation Attempts": "lucide:scale",
  "Scheduling and Prohibition": "lucide:scale",
  "Prohibition and International Control": "lucide:scale",
  "Prohibition and Research Hiatus": "lucide:scale",
  "Post-Scheduling Era": "lucide:scale",
  "Illicit Use and Regulatory Response": "lucide:scale",
  "Recognition of Abuse Potential": "lucide:scale",
  "Traditional Use": "lucide:leaf",
  "Traditional Use in Southern Africa": "lucide:leaf",
  "Traditional Use in Central Africa": "lucide:leaf",
  "Traditional Use in Southeast Asia": "lucide:leaf",
  "Traditional Use in the Americas": "lucide:leaf",
  "Traditional Use and Etymology": "lucide:leaf",
  "Traditional Ceremonial Practice": "lucide:leaf",
  "Traditional Cultural Practices": "lucide:leaf",
  "Traditional Medicine": "lucide:leaf",
  "Traditional Ayurvedic Uses": "lucide:leaf",
  "Traditional and Spiritual Use": "lucide:leaf",
  "Traditional Religious and Spiritual Use": "lucide:leaf",
  "Ancient Origins and Traditional Use": "lucide:leaf",
  "Ancient and Indigenous Use": "lucide:leaf",
  "Ancient and Early Use": "lucide:leaf",
  "Ancient Use and Archaeological Evidence": "lucide:leaf",
  "Indigenous Origins and Archaeological Evidence": "lucide:leaf",
  "Mesoamerican Traditions and Colonial Suppression": "lucide:leaf",
  "Religious Perspectives": "lucide:sun",
  "Religious and Spiritual Traditions": "lucide:sun",
  "Brazilian Syncretic Religions": "lucide:sun",
  "Temple of the True Inner Light": "lucide:sun",
  "Entity Encounters": "lucide:sun",
  "Cultural Significance": "lucide:sparkles",
  "Cultural References": "lucide:sparkles",
  "Cultural Emergence": "lucide:sparkles",
  "Cultural Associations": "lucide:sparkles",
  "Cultural Reception and Decline": "lucide:sparkles",
  "Cultural Representations and Industry Marketing": "lucide:sparkles",
  "Contemporary Cultural Status": "lucide:sparkles",
  "Prevalence and Cultural Significance": "lucide:sparkles",
  "Society and Culture": "lucide:sparkles",
  "Subcultural Associations": "lucide:sparkles",
  "Counterculture Movement": "lucide:sparkles",
  "The Summer of Love and STP Crisis": "lucide:sparkles",
  "Influence on Art and Music": "lucide:sparkles",
  "Recreational Use": "lucide:party-popper",
  "Emergence as a Recreational Drug": "lucide:party-popper",
  "Emergence in Recreational Markets": "lucide:party-popper",
  "Recreational Emergence and Distribution": "lucide:party-popper",
  "Recreational Emergence and Cultural Impact": "lucide:party-popper",
  "Emergence of Recreational Use and Abuse Concerns": "lucide:party-popper",
  "Recreational Use and Research Chemical Era": "lucide:party-popper",
  "Recreational Use and 'Purple Drank' Culture": "lucide:party-popper",
  "Recreational Use and the Romilar Era": "lucide:party-popper",
  "Recreational Use and Popular Culture": "lucide:party-popper",
  "Recreational Use and Decline": "lucide:party-popper",
  "Recreational and Non-Medical Use": "lucide:party-popper",
  "Recreational Culture": "lucide:party-popper",
  "Recreational Community Use": "lucide:party-popper",
  "Rise of Recreational Use": "lucide:party-popper",
  "Rise to Popularity": "lucide:party-popper",
  "Emergence as a Club Drug": "lucide:party-popper",
  "Non-Medical Use": "lucide:party-popper",
  "Emergence of Psychoactive Interest": "lucide:party-popper",
  "Emergence as a Research Chemical": "lucide:test-tubes",
  "Reemergence as a Research Chemical": "lucide:test-tubes",
  "Emergence as a Designer Drug": "lucide:test-tubes",
  "Emergence as a Street Drug": "lucide:test-tubes",
  "The Magical Half-Dozen": "lucide:test-tubes",
  "Operation Web Tryp": "lucide:test-tubes",
  "Military Applications": "lucide:shield",
  "Military Experimentation": "lucide:shield",
  "Military Use in World War II": "lucide:shield",
  "Military Applications and Australian Industry": "lucide:shield",
  "Wartime Use and Post-War Proliferation": "lucide:shield",
  "Scophedal and Wartime Applications": "lucide:shield",
  "Post-War Transfer to the United States": "lucide:shield",
  "Use as Truth Serum": "lucide:shield",
  "\"Truth Serum\" and Popular Culture": "lucide:shield",
  "Notable Individuals": "lucide:users",
  "Corporate Accountability and the Sackler Family": "lucide:users",
  "Notable Incidents": "lucide:alert-triangle",
  "Notable Deaths": "lucide:alert-triangle",
  "Media Attention and Deaths": "lucide:alert-triangle",
  "Public Health Crisis": "lucide:alert-triangle",
  "Illicit Production and the Overdose Crisis": "lucide:alert-triangle",
  "Reformulation and Public Health Crisis": "lucide:alert-triangle",
  "Krypton-Related Fatalities": "lucide:alert-triangle",
  "Contaminated Toy Recall": "lucide:alert-triangle",
  "Pearl Harbor Incident": "lucide:alert-triangle",
  "Recreational Abuse": "lucide:alert-circle",
  "Recreational Abuse and Cultural Impact": "lucide:alert-circle",
  "Abuse Concerns in Hong Kong": "lucide:alert-circle",
  "Misuse and Public Health Concerns": "lucide:alert-circle",
  "Misuse and Cultural Notoriety": "lucide:alert-circle",
  "Association with Drug-Facilitated Sexual Assault": "lucide:alert-circle",
  "Criminal Misuse": "lucide:alert-circle",
  "Emergence as Krokodil": "lucide:alert-circle",
  "Widespread Use and the Emergence of Heroin": "lucide:alert-circle",
  "Use in Capital Punishment": "lucide:gavel",
  "Capital Punishment and Euthanasia": "lucide:gavel",
  "Use in Nazi Euthanasia Programs": "lucide:gavel",
  "Modern History": "lucide:clock",
  "Origins and Early History": "lucide:clock",
  "United States History": "lucide:clock",
  "Social History in the United States": "lucide:clock",
  "Internet Era and Contemporary Use": "lucide:clock",
  "European Colonial Era": "lucide:clock",
  "Dietary Supplement and Bodybuilding Era": "lucide:clock",
  "Contemporary Use": "lucide:calendar",
  "Contemporary Prevalence": "lucide:calendar",
  "Contemporary Use and Availability": "lucide:calendar",
  "Contemporary Internet Culture": "lucide:calendar",
  "Contemporary Developments": "lucide:calendar",
  "Contemporary Production and Trafficking": "lucide:calendar",
  "Reformulation and Contemporary Status": "lucide:calendar",
  "Modern Documentation and Use": "lucide:calendar",
  "Modern Expansion": "lucide:calendar",
  "Modern Popularization": "lucide:calendar",
  "Modern Rediscovery": "lucide:calendar",
  "International Adoption": "lucide:globe",
  "International Introduction": "lucide:globe",
  "International Availability": "lucide:globe",
  "Introduction to Europe": "lucide:globe",
  "Introduction to the United States": "lucide:globe",
  "Popularity in the Netherlands": "lucide:globe",
  "South Africa": "lucide:globe",
  "Origins and Spread Through Oceania": "lucide:globe",
  "Western Contact and Global Spread": "lucide:globe",
  "Colonial Encounter": "lucide:globe",
  "Colonial Economic Impact": "lucide:globe",
  "European Documentation and Isolation": "lucide:globe",
  "Global Production and Trade": "lucide:factory",
  "Global Production and Distribution": "lucide:factory",
  "Global Trafficking Networks": "lucide:factory",
  "Industrial Production and Applications": "lucide:factory",
  "Agricultural and Industrial Applications": "lucide:factory",
  "Alleged Clandestine Production": "lucide:factory",
  "Media Coverage and Misinformation": "lucide:newspaper",
  "Media Portrayal and the Violence Narrative": "lucide:newspaper",
  "Efficacy Controversy": "lucide:newspaper",
  "Off-Label Marketing Controversy": "lucide:newspaper",
  "Marketing Controversies": "lucide:newspaper",
  "Emerging Safety Concerns": "lucide:newspaper",
  "First Human Reports": "lucide:bookmark",
  "Documentation and Early Detection": "lucide:bookmark",
  Etymology: "lucide:bookmark",
  Nomenclature: "lucide:bookmark",
  "Street Terminology": "lucide:bookmark",
  "Historical Use as Poison": "lucide:bookmark",
  "Association with European Witchcraft": "lucide:bookmark",
  "Toad Venom": "lucide:bookmark",
  "Botanical Classification": "lucide:bookmark",
  "Botanical Classification and Chemical Investigation": "lucide:bookmark",
  "Other Notable Uses": "lucide:bookmark",
  "Origins and Ancient Trade": "lucide:bookmark",
  "Doping Controversies in Sports": "lucide:trophy",
  "Dietary Supplements and Athletic Use": "lucide:trophy",
  "Use in Performance Settings": "lucide:trophy",
  "Cosmonautic Use": "lucide:rocket",
  "United States: 'Gas Station Heroin'": "lucide:store",
};

const KEYWORD_ICON_MAP: Record<string, IconName> = {
  discovery: "lucide:flask-conical",
  synthesis: "lucide:flask-conical",
  isolation: "lucide:flask-conical",
  research: "lucide:microscope",
  scientific: "lucide:microscope",
  studies: "lucide:microscope",
  medical: "lucide:stethoscope",
  clinical: "lucide:stethoscope",
  therapeutic: "lucide:stethoscope",
  treatment: "lucide:stethoscope",
  psychiatric: "lucide:stethoscope",
  pharmaceutical: "lucide:pill",
  formulation: "lucide:pill",
  approval: "lucide:pill",
  commercial: "lucide:building-2",
  market: "lucide:building-2",
  regulatory: "lucide:scale",
  scheduling: "lucide:scale",
  prohibition: "lucide:scale",
  traditional: "lucide:leaf",
  indigenous: "lucide:leaf",
  ancient: "lucide:leaf",
  ceremonial: "lucide:leaf",
  religious: "lucide:sun",
  spiritual: "lucide:sun",
  cultural: "lucide:sparkles",
  counterculture: "lucide:sparkles",
  subcultural: "lucide:sparkles",
  recreational: "lucide:party-popper",
  "club drug": "lucide:party-popper",
  "research chemical": "lucide:test-tubes",
  "designer drug": "lucide:test-tubes",
  military: "lucide:shield",
  "truth serum": "lucide:shield",
  wartime: "lucide:shield",
  notable: "lucide:users",
  individuals: "lucide:users",
  incident: "lucide:alert-triangle",
  deaths: "lucide:alert-triangle",
  crisis: "lucide:alert-triangle",
  fatalities: "lucide:alert-triangle",
  abuse: "lucide:alert-circle",
  misuse: "lucide:alert-circle",
  "capital punishment": "lucide:gavel",
  euthanasia: "lucide:gavel",
  history: "lucide:clock",
  era: "lucide:clock",
  contemporary: "lucide:calendar",
  modern: "lucide:calendar",
  international: "lucide:globe",
  colonial: "lucide:globe",
  global: "lucide:globe",
  production: "lucide:factory",
  trafficking: "lucide:factory",
  media: "lucide:newspaper",
  controversy: "lucide:newspaper",
  doping: "lucide:trophy",
  athletic: "lucide:trophy",
};

export function getIconForHistoryHeading(heading: string): IconName {
  if (EXACT_HEADING_ICONS[heading]) {
    return EXACT_HEADING_ICONS[heading];
  }

  const lowerHeading = heading.toLowerCase();
  for (const [keyword, icon] of Object.entries(KEYWORD_ICON_MAP)) {
    if (lowerHeading.includes(keyword)) {
      return icon;
    }
  }

  return "lucide:book-open";
}
