CREATE UNIQUE INDEX "articleDraftReceipts_by_owner_change_unique" ON "articleDraftReceipts" USING btree ("ownerEmail","changeId");--> statement-breakpoint
CREATE UNIQUE INDEX "articleDrafts_by_owner_slug_unique" ON "articleDrafts" USING btree ("ownerEmail","slug");--> statement-breakpoint
CREATE UNIQUE INDEX "articleRevisions_by_actor_change_unique" ON "articleRevisions" USING btree ("actorEmail","changeId");--> statement-breakpoint
CREATE UNIQUE INDEX "changeProposals_by_created_at_unique" ON "changeProposals" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "contentRevisions_by_operation_unique" ON "contentRevisions" USING btree ("table","key","operationId");--> statement-breakpoint
CREATE UNIQUE INDEX "contributorAvatarHistory_by_profile_id_and_media_digest_unique" ON "contributorAvatarHistory" USING btree ("profile_id","media_digest");--> statement-breakpoint
CREATE UNIQUE INDEX "contributorIdentitySnapshotMaterializations_by_snapsho_bc392845" ON "contributorIdentitySnapshotMaterializations" USING btree ("snapshot_digest");--> statement-breakpoint
CREATE UNIQUE INDEX "contributorProfiles_by_key_unique" ON "contributorProfiles" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "copyBlocks_by_key_unique" ON "copyBlocks" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "inviteCodes_by_code_hash_unique" ON "inviteCodes" USING btree ("codeHash");--> statement-breakpoint
CREATE UNIQUE INDEX "mailingListSubscribers_by_email_list_unique" ON "mailingListSubscribers" USING btree ("email","list");--> statement-breakpoint
CREATE UNIQUE INDEX "publicReadIndexState_by_name_unique" ON "publicReadIndexState" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationArtistTaxonomy_by_key_unique" ON "replicationArtistTaxonomy" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationDuplicateReconciliations_by_component_id_unique" ON "replicationDuplicateReconciliations" USING btree ("component_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationDuplicateReconciliations_by_suppressed_repl_76896446" ON "replicationDuplicateReconciliations" USING btree ("suppressed_replication_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationIdentityProfileBindings_by_artist_id_unique" ON "replicationIdentityProfileBindings" USING btree ("artist_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationIdentitySocialOperationItems_by_item_operat_c5ce8bf3" ON "replicationIdentitySocialOperationItems" USING btree ("item_operation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationIdentitySocialOperations_by_operation_id_unique" ON "replicationIdentitySocialOperations" USING btree ("operation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationIdentitySocialOperations_by_rollback_of_unique" ON "replicationIdentitySocialOperations" USING btree ("rollback_of");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationSocialAssets_by_entity_kind_and_entity_key__b9c43fd4" ON "replicationSocialAssets" USING btree ("entity_kind","entity_key","variant");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationSourceAttribution_by_replication_id_unique" ON "replicationSourceAttribution" USING btree ("replication_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replicationTaxonomyEvidence_by_replication_digest_unique" ON "replicationTaxonomyEvidence" USING btree ("replication_id","taxonomy_source_digest");--> statement-breakpoint
CREATE UNIQUE INDEX "replications_by_slug_unique" ON "replications" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "replications_by_source_catalog_id_unique" ON "replications" USING btree ("source_catalog_id");--> statement-breakpoint
CREATE UNIQUE INDEX "replications_by_taxonomy_record_key_unique" ON "replications" USING btree ("taxonomy_record_key");--> statement-breakpoint
CREATE UNIQUE INDEX "tripReports_by_slug_unique" ON "tripReports" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "warningBannerPresets_by_key_unique" ON "warningBannerPresets" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "warningBannerRevisions_by_key_unique" ON "warningBannerRevisions" USING btree ("key");--> statement-breakpoint
CREATE UNIQUE INDEX "warningBannerRevisions_by_change_unique" ON "warningBannerRevisions" USING btree ("changeId");