// GENERATED FILE. Do not edit by hand.
// Producer: scripts/postgres/generateFunctionRegistry.ts
// Inputs: runtime/functionOwnership.json and owned function modules.

import type { ApiFromModules } from "./server";
import type * as articleFeedback from "../../../server/articleFeedback";
import type * as articleLifecycle from "../../../server/articleLifecycle";
import type * as articleSources from "../../../server/articleSources";
import type * as authorAttribution from "../../../server/authorAttribution";
import type * as bindingSiteMigration from "../../../server/bindingSiteMigration";
import type * as categoryLayout from "../../../server/categoryLayout";
import type * as changeProposalReview from "../../../server/changeProposalReview";
import type * as changeProposals from "../../../server/changeProposals";
import type * as changelog from "../../../server/changelog";
import type * as citationEvidence from "../../../server/citationEvidence";
import type * as contentRevisions from "../../../server/contentRevisions";
import type * as contributorProfileMerges from "../../../server/contributorProfileMerges";
import type * as contributorProfiles from "../../../server/contributorProfiles";
import type * as copyBlocks from "../../../server/copyBlocks";
import type * as effectIndexArchive from "../../../server/effectIndexArchive";
import type * as effectIndexArticles from "../../../server/effectIndexArticles";
import type * as indexLayouts from "../../../server/indexLayouts";
import type * as inviteCodes from "../../../server/inviteCodes";
import type * as mailingList from "../../../server/mailingList";
import type * as memberships from "../../../server/memberships";
import type * as moleculeClassTemplates from "../../../server/moleculeClassTemplates";
import type * as moleculeEditor from "../../../server/moleculeEditor";
import type * as moleculeOverrides from "../../../server/moleculeOverrides";
import type * as prompts from "../../../server/prompts";
import type * as publicArtistCredits from "../../../server/publicArtistCredits";
import type * as publicOverview from "../../../server/publicOverview";
import type * as publicReadIndexes from "../../../server/publicReadIndexes";
import type * as publicReplicationIdentitySocial from "../../../server/publicReplicationIdentitySocial";
import type * as publicationRecovery from "../../../server/publicationRecovery";
import type * as quotes from "../../../server/quotes";
import type * as reagentTestContract from "../../../server/reagentTestContract";
import type * as reagentTests from "../../../server/reagentTests";
import type * as replicationAttribution from "../../../server/replicationAttribution";
import type * as replicationContextualEditing from "../../../server/replicationContextualEditing";
import type * as replicationDates from "../../../server/replicationDates";
import type * as replicationDuplicates from "../../../server/replicationDuplicates";
import type * as replicationIdentitySocial from "../../../server/replicationIdentitySocial";
import type * as replicationPlaylists from "../../../server/replicationPlaylists";
import type * as replicationTaxonomy from "../../../server/replicationTaxonomy";
import type * as replications from "../../../server/replications";
import type * as siteConfig from "../../../server/siteConfig";
import type * as siteFeedback from "../../../server/siteFeedback";
import type * as subjectiveEffects from "../../../server/subjectiveEffects";
import type * as substanceGalleries from "../../../server/substanceGalleries";
import type * as substanceIndex from "../../../server/substanceIndex";
import type * as tripReportContract from "../../../server/tripReportContract";
import type * as tripReportSubmissions from "../../../server/tripReportSubmissions";
import type * as tripReports from "../../../server/tripReports";
import type * as warningBanners from "../../../server/warningBanners";

export type Api = ApiFromModules<{
  articleFeedback: typeof articleFeedback;
  articleLifecycle: typeof articleLifecycle;
  articleSources: typeof articleSources;
  authorAttribution: typeof authorAttribution;
  bindingSiteMigration: typeof bindingSiteMigration;
  categoryLayout: typeof categoryLayout;
  changeProposalReview: typeof changeProposalReview;
  changeProposals: typeof changeProposals;
  changelog: typeof changelog;
  citationEvidence: typeof citationEvidence;
  contentRevisions: typeof contentRevisions;
  contributorProfileMerges: typeof contributorProfileMerges;
  contributorProfiles: typeof contributorProfiles;
  copyBlocks: typeof copyBlocks;
  effectIndexArchive: typeof effectIndexArchive;
  effectIndexArticles: typeof effectIndexArticles;
  indexLayouts: typeof indexLayouts;
  inviteCodes: typeof inviteCodes;
  mailingList: typeof mailingList;
  memberships: typeof memberships;
  moleculeClassTemplates: typeof moleculeClassTemplates;
  moleculeEditor: typeof moleculeEditor;
  moleculeOverrides: typeof moleculeOverrides;
  prompts: typeof prompts;
  publicArtistCredits: typeof publicArtistCredits;
  publicOverview: typeof publicOverview;
  publicReadIndexes: typeof publicReadIndexes;
  publicReplicationIdentitySocial: typeof publicReplicationIdentitySocial;
  publicationRecovery: typeof publicationRecovery;
  quotes: typeof quotes;
  reagentTestContract: typeof reagentTestContract;
  reagentTests: typeof reagentTests;
  replicationAttribution: typeof replicationAttribution;
  replicationContextualEditing: typeof replicationContextualEditing;
  replicationDates: typeof replicationDates;
  replicationDuplicates: typeof replicationDuplicates;
  replicationIdentitySocial: typeof replicationIdentitySocial;
  replicationPlaylists: typeof replicationPlaylists;
  replicationTaxonomy: typeof replicationTaxonomy;
  replications: typeof replications;
  siteConfig: typeof siteConfig;
  siteFeedback: typeof siteFeedback;
  subjectiveEffects: typeof subjectiveEffects;
  substanceGalleries: typeof substanceGalleries;
  substanceIndex: typeof substanceIndex;
  tripReportContract: typeof tripReportContract;
  tripReportSubmissions: typeof tripReportSubmissions;
  tripReports: typeof tripReports;
  warningBanners: typeof warningBanners;
}>;
