// Auto-generated - do not edit
export const substanceName = "Hydroxyzine";
export const sources = [{"id":"drugbank","fileName":"DRUGBANK - Hydroxyzine.md","displayName":"DrugBank","size":30466},{"id":"protestkit","fileName":"PROTESTKIT - Hydroxyzine.json","displayName":"Protest Kit","size":3376},{"id":"tripsit-factsheets","fileName":"TRIPSIT_FACTSHEETS - Hydroxyzine.md","displayName":"TripSit Factsheets","size":633},{"id":"wikipedia","fileName":"WIKIPEDIA - Hydroxyzine.md","displayName":"Wikipedia","size":11366}];
export const contents: Record<string, string> = {
  "drugbank": `# Hydroxyzine
*Source: https://go.drugbank.com/drugs/DB00557*

## Overview

### Description

This compound belongs to the class of organic compounds known as diphenylmethanes. These are compounds containing a diphenylmethane moiety, which consists of a methane wherein two hydrogen atoms are replaced by two phenyl groups.

### Background

Hydroxyzine is a first-generation histamine H
1
-receptor antagonist of the dephenylmethane and piperazine classes that exhibits sedative, anxiolytic, and antiemetic properties.
2
,
12
It was first developed in 1955,
10
and has since remained a relatively common treatment for allergic conditions such as pruritus, urticaria, dermatoses, and histamine-mediated pruritus.
18
The active metabolite of hydroxyzine,
cetirizine
, is also available as an active ingredient in allergic medications, and is responsible for much of its hydroxyzine's antihistaminic effect.
13
Hydroxyzine is also used for generalized anxiety disorder, tension caused by psychoneurosis, and other conditions with manifestations of anxiety.
18

### Indication

Hydroxyzine is indicated for the symptomatic relief of anxiety and tension associated with psychoneuroses, and as an adjunct in organic disease states in which anxiety is manifested.
18
It is also indicated in the treatment of histamine-mediated pruritus and pruritus due to allergic conditions such as chronic urticaria.
18
Canadian labeling states that hydroxyzine is also indicated in adults and children as a premedication prior to medical procedures, such as dental surgery.
15
It is also used in the control of nausea and vomiting, excluding nausea and vomiting of pregnancy.
15

### Pharmacodynamics

Hydroxyzine blocks the activity of histamine to relieve allergic symptoms such as pruritus.
18
Activity at off-targets also allows for its use as a sedative anxiolytic and an antiemetic in certain disease states.
15
Hydroxyzine is relatively fast-acting, with an onset of effect that occurs between 15 and 60 minutes and a duration of action between 4-6 hours.
2
Hydroxyzine may potentiate the effects of central nervous system (CNS) depressants following general anesthesia - patients maintained on hydroxyzine should receive reduced doses of any CNS depressants required.
18
Hydroxyzine is reported to prolong the QT/QTc interval based on postmarketing reports of rare events of Torsade de Pointes, cardiac arrest, and sudden death, and should be used with caution in patients with an increased baseline risk for QTc prolongation.
15
,
10

### Mechanism of Action

Histamine H1 receptor
Inverse agonist

### Absorption

The absolute bioavailability of hydroxyzine has not been ascertained, as intravenous formulations are unavailable due to a risk of hemolysis.
2
Hydroxyzine is rapidly absorbed from the gastrointestinal tract upon oral administration,
18
reaching its maximum plasma concentration (T
max
) approximately 2 hours following administration.
9

### Metabolism

Hydroxyzine is metabolized in the liver
2
by CYP3A4 and CYP3A5.
18
While the precise metabolic fate of hydroxyzine is unclear, its main and active metabolite (~45 to 60% of an orally administered dose),
13
generated by oxidation of its alcohol moiety to a carboxylic acid, is the second-generation antihistamine
cetirizine
.
2
Hydroxyzine is likely broken down into several other metabolites, though specific structures and pathways have not been elucidated in humans.
7
Hover over products below to view reaction partners
Hydroxyzine
Cetirizine

### Half-life

The half-life of hydroxyzine is reportedly 14-25 hours,
2
and appears to be, on average, shorter in children (~7.1 hours) than in adults (~20 hours).
6
Elimination half-life is prolonged in the elderly, averaging approximately 29 hours,
3
and is likely to be similarly prolonged in patients with renal or hepatic impairment.
15

### Toxicity

The oral LD
50
is 840 mg/kg in rats and 400 mg/kg in mice.
16
Overdose from hydroxyzine is most commonly characterized by hypersedation, but may also manifest as convulsions, stupor, nausea, and vomiting.
18
In cases of overdose, consider the induction of vomiting and the use of gastric lavage. Other treatment should involve general symptomatic and supportive care. Hypotension may be controlled by intravenous fluids and pressors, and caffeine and sodium benzoate injection may be used to counteract any observed CNS depressant effects. Hemodialysis is unlikely to provide any benefit in the treatment hydroxyzine overdose.
18

### Drug Interactions

This information should not be interpreted without the help of a healthcare provider. If you believe you are experiencing an interaction, contact a healthcare provider immediately. The absence of an interaction does not necessarily mean no interactions exist.

1,2-Benzodiazepine
Hydroxyzine may increase the central nervous system depressant (CNS depressant) activities of 1,2-Benzodiazepine.
Abametapir
The serum concentration of Hydroxyzine can be increased when it is combined with Abametapir.
Abatacept
The metabolism of Hydroxyzine can be increased when combined with Abatacept.
Acalabrutinib
The metabolism of Hydroxyzine can be decreased when combined with Acalabrutinib.
Acebutolol
The risk or severity of QTc prolongation can be increased when Acebutolol is combined with Hydroxyzine.

### Food Interactions

Avoid alcohol. Co-administration with alcohol may potentiate the CNS adverse effects of hydroxyzine.
Avoid grapefruit products. Co-administration with grapefruit inhibits hydroxyzine metabolism and can result in elevated serum concentrations.

## Chemical Information

**DrugBank ID:** DB00557

**Synonyms:** Hidroxizina
Hychotine
Hydroksyzyny
Hydroxine
Hydroxizine
Hydroxizinum
Hydroxycine
Hydroxyzin
Hydroxyzine
Hydroxyzinum
Idrossizina

**Chemical Formula:** C
21
H
27
ClN
2
O
2

**SMILES:** OCCOCCN1CCN(CC1)C(C1=CC=CC=C1)C1=CC=C(Cl)C=C1

**Weight:** Average: 374.904
Monoisotopic: 374.176105825

**IUPAC Name:** 2-(2-{4-[(4-chlorophenyl)(phenyl)methyl]piperazin-1-yl}ethoxy)ethan-1-ol

## Additional Information

### Modality

Small Molecule

### Patents

0

### Indicated Conditions

7

### Phase 0

0

### Phase 1

1

### Phase 2

2

### Phase 3

4

### Phase 4

12

### Therapeutic Categories

Histamine
Antagonists
Miscellaneous Anxiolytics Sedatives and
Hypnotics

### Summary

Hydroxyzine
is an antihistamine used to treat anxiety and tension associated with psychoneuroses, as well as allergic conditions such as pruritus and chronic urticaria.

### Brand Names

Atarax, Vistaril

### Generic Name

Hydroxyzine

### DrugBank Accession Number

DB00557

### Groups

Approved, Investigational

### Structure

3D
Download
MOL
SDF
3D-SDF
PDB
SMILES
InChI
Similar Structures
Structure for Hydroxyzine (DB00557)
×
Close

### External IDs

U.C.B-4492

### Associated Conditions

Indication Type
Indication
Combined Product Details
Approval Level
Age Group
Patient Characteristics
Dose Form
Prevention of
Anxiety
••••••••••••
Create Account
Adjunct therapy in treatment of
Anxiety
••••••••••••
Create Account
Symptomatic treatment of
Anxiety
••••••••••••
Create Account
Symptomatic treatment of
Nausea and vomiting
••••••••••••
Create Account
Treatment of
Pruritus
••••••••••••
Create Account
Create Account

### Mechanism of action

The H
1
histamine receptor is responsible for mediating hypersensitivity and allergic reactions. Exposure to an allergen results in degranulation of mast cells and basophils, which then release histamine and other inflammatory mediators. Histamine binds to, and activates, H
1
receptors, which results in the further release of pro-inflammatory cytokines, such as interleukins, from basophils and mast cells. These downstream effects of histamine binding are responsible for a wide variety of allergic symptoms, such as pruritus, rhinorrhea, and watery eyes.
11
Hydroxyzine is a potent inverse agonist of histamine H
1
-receptors
2
- inverse agonists are agents that are considered to have a "negative efficacy", so rather than simply blocking activity at a receptor they actively dampen its activity.
14
Inverse agonism at these receptors is responsible for hydroxyzine's efficacy in the treatment of histaminic edema, flare, and pruritus.
Hydroxyzine is not a cortical depressant, so its sedative properties likely occur at the subcortical level of the CNS.
18
These sedative properties allow activity as an anxiolytic. Antiemetic efficacy is likely secondary to activity at off-targets.
13
Target
Actions
Organism
A
Histamine H1 receptor
inverse agonist
Humans
U
Voltage-gated inwardly rectifying potassium channel KCNH2
inhibitor
Humans

### Volume of distribution

The mean volume of distribution is 16.0 ± 3.0 L/kg. Higher concentrations are found in the skin than in the plasma.
2

### Protein binding

Hydroxyzine has been shown to bind to human albumin
in vitro
,
8
but the extent of protein binding in plasma has not been evaluated.

### Route of elimination

Approximately 70% of hydroxyzine's active metabolite, cetirizine, is excreted unchanged in the urine.
3
The precise extent of renal and fecal excretion in humans has not been determined.
18

### Clearance

Clearance of hydroxyzine has been reported to be 31.1 ± 11.1 mL/min/kg in children and 9.8 ± 3.3 mL/min/kg in adults.
6

### Pathways

Pathway
Category
Hydroxyzine H1-Antihistamine Action
Drug action

### Product Ingredients

Ingredient
UNII
CAS
InChI Key
Hydroxyzine hydrochloride
76755771U3
2192-20-3
ANOMHKZSQFYSBR-UHFFFAOYSA-N
Hydroxyzine pamoate
M20215MUFR
10246-75-0
ASDOKGIIKXGMNB-UHFFFAOYSA-N

### Product Images

Previous
Next

### International/Other Brands

Hyzine (Hyrex)
/
Masmoran (Pfizer)
/
Rezine
/
Vistaject-50
/
Vistazine

### Brand Name Prescription Products

Name
Dosage
Strength
Route
Labeller
Marketing Start
Marketing End
Region
Image
Atarax
Syrup
10 mg / 5 mL
Oral
Searchlight Pharma Inc
1956-12-31
Not applicable
Canada
Atarax
Tablet
100 mg/1
Oral
Roerig
2006-06-20
2016-06-16
US
Atarax
Tablet
10 mg/1
Oral
Roerig
2006-06-20
2016-06-16
US
Atarax
Tablet
50 mg/1
Oral
Roerig
2006-06-20
2016-06-16
US
Atarax
Syrup
10 mg/5mL
Oral
Roerig
2006-06-20
2016-06-16
US

### Generic Prescription Products

Name
Dosage
Strength
Route
Labeller
Marketing Start
Marketing End
Region
Image
Hydroxyzine
Tablet, film coated
50 mg/1
Oral
Major Pharmaceuticals
2007-03-20
Not applicable
US
Hydroxyzine
Tablet, film coated
25 mg/1
Oral
Pliva, Inc.
2010-08-02
2010-12-05
US
Hydroxyzine
Tablet, film coated
25 mg/1
Oral
Ncs Health Care Of Ky, Inc Dba Vangard Labs
2007-03-20
Not applicable
US
Hydroxyzine
Tablet, film coated
10 mg/1
Oral
Blenheim Pharmacal, Inc.
2009-12-28
Not applicable
US
Hydroxyzine
Tablet, film coated
25 mg/1
Oral
Major Pharmaceuticals
2007-03-20
Not applicable
US

### Over the Counter Products

Name
Dosage
Strength
Route
Labeller
Marketing Start
Marketing End
Region
Image
ซีนิซ
Tablet
10 mg
Oral
บริษัท ไทยนครพัฒนา จำกัด
2007-03-26
Not applicable
Thailand
ดร็อกซิม
Tablet
25 mg
Oral
บริษัท บุคคโล เทรดดิ้ง จำกัด  จำกัด
2008-06-25
Not applicable
Thailand

### Mixture Products

Name
Ingredients
Dosage
Route
Labeller
Marketing Start
Marketing End
Region
Image
ATARAX FILM TABLET, 30 ADET
Hydroxyzine
(10 mg)
+ Hydroxyzine
(25 mg)
Tablet
Oral
Ucb Pharma S.A.
1997-03-05
Not applicable
Turkey
ATARAX FILM TABLET, 30 ADET
Hydroxyzine
(10 mg)
+ Hydroxyzine
(25 mg)
Tablet
Oral
Ucb Pharma S.A.
1997-03-05
Not applicable
Turkey

### Unapproved/Other Products

Name
Ingredients
Dosage
Route
Labeller
Marketing Start
Marketing End
Region
Image
MKH Dose Pack
Hydroxyzine hydrochloride
(10 mg/1)
+
Ketamine hydrochloride
(25 mg/1)
+
Midazolam
(3 mg/1)
Troche
Sublingual
Imprimis Njof, Llc
2019-03-04
Not applicable
US

### ATC Codes

N05BB01 — Hydroxyzine
N05BB — Diphenylmethane derivatives
N05B — ANXIOLYTICS
N05 — PSYCHOLEPTICS
N — NERVOUS SYSTEM
N05BB51 — Hydroxyzine, combinations
N05BB — Diphenylmethane derivatives
N05B — ANXIOLYTICS
N05 — PSYCHOLEPTICS
N — NERVOUS SYSTEM

### Drug Categories

Anti-Anxiety Agents
Antipruritics
Central Nervous System Depressants
Cytochrome P-450 CYP2D6 Inhibitors
Cytochrome P-450 CYP2D6 Inhibitors (strength unknown)
Cytochrome P-450 CYP3A Substrates
Cytochrome P-450 CYP3A4 Substrates
Cytochrome P-450 CYP3A5 Substrates
Cytochrome P-450 Enzyme Inhibitors
Cytochrome P-450 Substrates
Dermatologicals
Diphenylmethane Derivatives
Histamine Agents
Histamine Antagonists
Histamine H1 Antagonists
Histamine Receptor Antagonists
Miscellaneous Anxiolytics Sedatives and Hypnotics
Nervous System
Neurotransmitter Agents
P-glycoprotein substrates
Piperazines
Potential QTc-Prolonging Agents
Psycholeptics
QTc Prolonging Agents

### Chemical TaxonomyProvided byClassyfire

Description
This compound belongs to the class of organic compounds known as diphenylmethanes. These are compounds containing a diphenylmethane moiety, which consists of a methane wherein two hydrogen atoms are replaced by two phenyl groups.
Kingdom
Organic compounds
Super Class
Benzenoids
Class
Benzene and substituted derivatives
Sub Class
Diphenylmethanes
Direct Parent
Diphenylmethanes
Alternative Parents
N-alkylpiperazines
/
Chlorobenzenes
/
Aralkylamines
/
Aryl chlorides
/
Trialkylamines
/
Dialkyl ethers
/
Azacyclic compounds
/
Primary alcohols
/
Organopnictogen compounds
/
Organochlorides
/
Hydrocarbon derivatives
show 1 more
Substituents
1,4-diazinane
/
Alcohol
/
Amine
/
Aralkylamine
/
Aromatic heteromonocyclic compound
/
Aryl chloride
/
Aryl halide
/
Azacycle
/
Chlorobenzene
/
Dialkyl ether
/
Diphenylmethane
/
Ether
/
Halobenzene
/
Hydrocarbon derivative
/
N-alkylpiperazine
/
Organic nitrogen compound
/
Organic oxygen compound
/
Organochloride
/
Organohalogen compound
/
Organoheterocyclic compound
/
Organonitrogen compound
/
Organooxygen compound
/
Organopnictogen compound
/
Piperazine
/
Primary alcohol
/
Tertiary aliphatic amine
/
Tertiary amine
show 17 more
Molecular Framework
Aromatic heteromonocyclic compounds
External Descriptors
monochlorobenzenes, N-alkylpiperazine, hydroxyether (
CHEBI:5818
)

### Kingdom

Organic compounds

### Super Class

Benzenoids

### Class

Benzene and substituted derivatives

### Sub Class

Diphenylmethanes

### Direct Parent

Diphenylmethanes

### Alternative Parents

N-alkylpiperazines
/
Chlorobenzenes
/
Aralkylamines
/
Aryl chlorides
/
Trialkylamines
/
Dialkyl ethers
/
Azacyclic compounds
/
Primary alcohols
/
Organopnictogen compounds
/
Organochlorides
/
Hydrocarbon derivatives
show 1 more

### Substituents

1,4-diazinane
/
Alcohol
/
Amine
/
Aralkylamine
/
Aromatic heteromonocyclic compound
/
Aryl chloride
/
Aryl halide
/
Azacycle
/
Chlorobenzene
/
Dialkyl ether
/
Diphenylmethane
/
Ether
/
Halobenzene
/
Hydrocarbon derivative
/
N-alkylpiperazine
/
Organic nitrogen compound
/
Organic oxygen compound
/
Organochloride
/
Organohalogen compound
/
Organoheterocyclic compound
/
Organonitrogen compound
/
Organooxygen compound
/
Organopnictogen compound
/
Piperazine
/
Primary alcohol
/
Tertiary aliphatic amine
/
Tertiary amine
show 17 more

### Molecular Framework

Aromatic heteromonocyclic compounds

### External Descriptors

monochlorobenzenes, N-alkylpiperazine, hydroxyether (
CHEBI:5818
)

### Affected organisms

Humans and other mammals

### UNII

30S50YM8OG

### CAS number

68-88-2

### InChI Key

ZQDWXGKKHFNSQK-UHFFFAOYSA-N

### InChI

InChI=1S/C21H27ClN2O2/c22-20-8-6-19(7-9-20)21(18-4-2-1-3-5-18)24-12-10-23(11-13-24)14-16-26-17-15-25/h1-9,21,25H,10-17H2

### Synthesis Reference

U.S. Patent 2,899,436.

### General References

Clark BG, Araki M, Brown HW: Hydroxyzine-associated tardive dyskinesia. Ann Neurol. 1982 Apr;11(4):435. [
Article
]
Altamura AC, Moliterno D, Paletta S, Maffini M, Mauri MC, Bareggi S: Understanding the pharmacokinetics of anxiolytic drugs. Expert Opin Drug Metab Toxicol. 2013 Apr;9(4):423-40. doi: 10.1517/17425255.2013.759209. Epub 2013 Jan 21. [
Article
]
Simons KJ, Watson WT, Chen XY, Simons FE: Pharmacokinetic and pharmacodynamic studies of the H1-receptor antagonist hydroxyzine in the elderly. Clin Pharmacol Ther. 1989 Jan;45(1):9-14. doi: 10.1038/clpt.1989.2. [
Article
]
Lee BH, Lee SH, Chu D, Hyun JW, Choe H, Choi BH, Jo SH: Effects of the histamine H(1) receptor antagonist hydroxyzine on hERG K(+) channels and cardiac action potential duration. Acta Pharmacol Sin. 2011 Sep;32(9):1128-37. doi: 10.1038/aps.2011.66. [
Article
]
Crowe A, Wright C: The impact of P-glycoprotein mediated efflux on absorption of 11 sedating and less-sedating antihistamines using Caco-2 monolayers. Xenobiotica. 2012 Jun;42(6):538-49. doi: 10.3109/00498254.2011.643256. Epub 2011 Dec 22. [
Article
]
Paton DM, Webster DR: Clinical pharmacokinetics of H1-receptor antagonists (the antihistamines). Clin Pharmacokinet. 1985 Nov-Dec;10(6):477-97. [
Article
]
Fouda HG, Hobbs DC, Stambaugh JE: Sensitive assay for determination of hydroxyzine in plasma and its human pharmacokinetics. J Pharm Sci. 1979 Nov;68(11):1456-8. doi: 10.1002/jps.2600681134. [
Article
]
Martinez-Gomez MA, Villanueva-Camanas RM, Sagrado S, Medina-Hernandez MJ: Evaluation of enantioselective binding of antihistamines to human serum albumin by ACE. Electrophoresis. 2007 Aug;28(15):2635-43. doi: 10.1002/elps.200600742. [
Article
]
Simons FE, Simons KJ, Frith EM: The pharmacokinetics and antihistaminic of the H1 receptor antagonist hydroxyzine. J Allergy Clin Immunol. 1984 Jan;73(1 Pt 1):69-75. doi: 10.1016/0091-6749(84)90486-x. [
Article
]
Schlit AF, Delaunois A, Colomar A, Claudio B, Cariolato L, Boev R, Valentin JP, Peters C, Sloan VS, Bentz JWG: Risk of QT prolongation and torsade de pointes associated with exposure to hydroxyzine: re-evaluation of an established drug. Pharmacol Res Perspect. 2017 Apr 21;5(3):e00309. doi: 10.1002/prp2.309. eCollection 2017 Jun. [
Article
]
Devillier P, Roche N, Faisy C: Clinical pharmacokinetics and pharmacodynamics of desloratadine, fexofenadine and levocetirizine : a comparative review. Clin Pharmacokinet. 2008;47(4):217-30. [
Article
]
Sawantdesai NS, Kale PP, Savai J: Evaluation of anxiolytic effects of aripiprazole and hydroxyzine as a combination in mice. J Basic Clin Pharm. 2016 Sep;7(4):97-104. doi: 10.4103/0976-0105.189429. [
Article
]
Gengo FM, Dabronzo J, Yurchak A, Love S, Miller JK: The relative antihistaminic and psychomotor effects of hydroxyzine and cetirizine. Clin Pharmacol Ther. 1987 Sep;42(3):265-72. doi: 10.1038/clpt.1987.145. [
Article
]
How drugs act: General principles. (2020). In Rang and Dale's Pharmacology (9th ed.). Edinburgh: Elsevier. [
ISBN:9780702080609
]
Health Canada Product Monograph: Hydroxyzine HCl oral capsules [
Link
]
CaymanChem: Hydroxyzine MSDS [
Link
]
FDA Approved Drug Products: Hydroxyzine HCl oral tablets [
Link
]
FDA Approved Drug Products: Vistaril (hydroxyzine pamoate) [
Link
]
FDA Approved Drug Products: VISTARIL (hydroxyzine pamoate) capsules and suspension [
Link
]
DailyMed: hydroxyzine hydrochloride injection [
Link
]

### External Links

Human Metabolome Database
HMDB0014697
KEGG Drug
D08054
KEGG Compound
C07045
PubChem Compound
3658
PubChem Substance
46508556
ChemSpider
3531
BindingDB
22875
RxNav
5553
ChEBI
5818
ChEMBL
CHEMBL896
Therapeutic Targets Database
DAP000324
PharmGKB
PA449943
RxList
RxList Drug Page
Drugs.com
Drugs.com Drug Page
PDRhealth
PDRhealth Drug Page
Wikipedia
Hydroxyzine

### Human Metabolome Database

HMDB0014697

### KEGG Drug

D08054

### KEGG Compound

C07045

### PubChem Compound

3658

### PubChem Substance

46508556

### ChemSpider

3531

### BindingDB

22875

### RxNav

5553

### ChEBI

5818

### ChEMBL

CHEMBL896

### Therapeutic Targets Database

DAP000324

### PharmGKB

PA449943

### RxList

RxList Drug Page

### Drugs.com

Drugs.com Drug Page

### PDRhealth

PDRhealth Drug Page

### Wikipedia

Hydroxyzine

### Manufacturers

Baxter healthcare corp anesthesia and critical care
Altana inc
App pharmaceuticals llc
Hospira inc
Luitpold pharmaceuticals inc
Pharmafair inc
Smith and nephew solopak div smith and nephew
Solopak medical products inc
Solopak laboratories inc
Watson laboratories inc
Wyeth ayerst laboratories
Organon usa inc
Pfizer laboratories div pfizer inc
Roerig div pfizer inc
Actavis mid atlantic llc
Alpharma us pharmaceuticals division
Hi tech pharmacal co inc
Kv pharmaceutical co
Vintage pharmaceuticals inc
Wockhardt eu operations (swiss) ag
Pfizer inc
Able laboratories inc
Actavis totowa llc
Amneal pharmaceutical
Halsey drug co inc
Heritage pharmaceuticals inc
Hetero drugs ltd unit iii
Invagen pharmaceuticals inc
Ivax pharmaceuticals inc
Kvk tech inc
Mutual pharmaceutical co inc
Mylan pharmaceuticals inc
Northstar healthcare holdings ltd
Pliva inc
Purepac pharmaceutical co
Quantum pharmics ltd
Sandoz inc
Sun pharmaceutical industries inc
Superpharm corp
Usl pharma inc
Vintage pharmaceuticals llc
Barr laboratories inc
Duramed pharmaceuticals inc sub barr laboratories inc
Ivax pharmaceuticals inc sub teva pharmaceuticals usa
Par pharmaceutical inc
Vangard laboratories inc div midway medical co
Teva pharmaceuticals usa inc

### Packagers

Advanced Pharmaceutical Services Inc.
American Regent
Amerisource Health Services Corp.
Anda Inc.
Apotheca Inc.
APP Pharmaceuticals
A-S Medication Solutions LLC
Atlantic Biologicals Corporation
Barr Pharmaceuticals
Blenheim Pharmacal
Bryant Ranch Prepack
C.O. Truxton Inc.
Caraco Pharmaceutical Labs
Cardinal Health
Caremark LLC
Carlisle Laboratories Inc.
Central Texas Community Health Centers
Clint Pharmaceutical Inc.
Co Med Pharmaceuticals Inc.
Comprehensive Consultant Services Inc.
Corepharma LLC
Darby Dental Supply Co. Inc.
Dept Health Central Pharmacy
Direct Dispensing Inc.
Direct Pharmaceuticals Inc.
Dispensing Solutions
Diversified Healthcare Services Inc.
Eon Labs
Glenmark Generics Ltd.
Goldline Laboratories Inc.
H and H Laboratories
H.J. Harkins Co. Inc.
Harris Pharmaceutical Inc.
Heartland Repack Services LLC
Heritage Pharmaceuticals
Hi Tech Pharmacal Co. Inc.
Innoviant Pharmacy Inc.
InvaGen Pharmaceuticals Inc.
Ivax Pharmaceuticals
Kaiser Foundation Hospital
Keltman Pharmaceuticals Inc.
KVK-Tech Inc.
Lake Erie Medical and Surgical Supply
Liberty Pharmaceuticals
Luitpold Pharmaceuticals Inc.
Major Pharmaceuticals
Martica Enterprises Inc.
Martin Surgical Supply
Medisca Inc.
Medvantx Inc.
Merit Pharmaceuticals
Merrell Pharmaceuticals Inc.
Monument Pharmaceutical Co. Inc.
Murfreesboro Pharmaceutical Nursing Supply
Mutual Pharmaceutical Co.
Mylan
National Pharmaceuticals
Nightingale Medical Of Indiana LLC
Northstar Rx LLC
Nucare Pharmaceuticals Inc.
Palmetto Pharmaceuticals Inc.
Patheon Inc.
Patient First Corp.
PCA LLC
PD-Rx Pharmaceuticals Inc.
Pfizer Inc.
Pharmaceutical Utilization Management Program VA Inc.
Pharmacy Service Center
Pharmedix
Physicians Total Care Inc.
Piramal Healthcare
Pliva Inc.
Preferred Pharmaceuticals Inc.
Prepackage Specialists
Prepak Systems Inc.
Prescript Pharmaceuticals
Prescription Dispensing Service Inc.
Qualitest
Rebel Distributors Corp.
Redpharm Drug
Remedy Repack
Resource Optimization and Innovation LLC
Sandhills Packaging Inc.
Southwood Pharmaceuticals
St Mary's Medical Park Pharmacy
Stat Rx Usa
Sun Pharmaceutical Industries Ltd.
Talbert Medical Management Corp.
UDL Laboratories
United Research Laboratories Inc.
Vangard Labs Inc.
Veratex Corp.
Vintage Pharmaceuticals Inc.
Watson Pharmaceuticals
Wockhardt Ltd.

### Dosage Forms

Form
Route
Strength
Capsule, liquid filled
Oral
25 mg
Tablet, film coated
Oral
50 mg
Tablet
Oral
10.00 mg
Capsule
Oral
25.000 mg
Injection, solution
Intramuscular
Syrup
Oral
Syrup
Oral
10 mg/5mL
Tablet
Oral
10 mg/1
Tablet
Oral
10.000 mg
Tablet
Oral
100 mg/1
Tablet
Oral
25 mg/1
Tablet
Oral
50 mg/1
Tablet, film coated
Oral
Syrup
Oral
200 ml
Solution
Intramuscular
50 mg / mL
Tablet, film coated
Oral
30 mg
Syrup
Oral
300 mg
Tablet
Oral
500 mg
Tablet
Oral
Tablet, chewable
Buccal
25 mg
Tablet, coated
Oral
50 mg
Solution
Intramuscular
100 mg
Solution
Oral
10 mg
Solution
Oral
250 mg
Syrup
Oral
250 mg
Solution
Oral
0.25 g
Tablet
Oral
2500000 mg
Syrup
Oral
0.25 g
Capsule
Oral
10 mg
Capsule
Oral
25 mg
Capsule
Oral
50 mg
Liquid
Oral
10 mg/5mL
Injection, solution
Intramuscular
50 mg/1mL
Solution
Oral
10 mg/5mL
Syrup
Oral
50 mg/25mL
Tablet, film coated
Oral
10 mg/1
Tablet, film coated
Oral
25 mg/1
Tablet, film coated
Oral
50 mg/1
Liquid
Intramuscular
50 mg / mL
Tablet, film coated
Oral
10.000 mg
Tablet, film coated
Oral
25.000 mg
Capsule
Oral
100 mg/1
Capsule
Oral
25 mg/1
Capsule
Oral
50 mg/1
Tablet, film coated
Oral
10 mg
Troche
Sublingual
Capsule
Oral
10 mg / cap
Capsule
Oral
25 mg / cap
Injection, solution
Intramuscular
25 mg/1mL
Syrup
Oral
10 mg / 5 mL
Solution / drops
Oral
10 ml
Solution / drops
Oral
20 ml
Solution
Intramuscular
50 mg/1mL
Suspension
Oral
25 mg/5mL
Tablet
Oral
25.000 mg
Tablet, coated
Oral
25 mg
Tablet
Oral
25 mg
Tablet
Oral
10 mg
Tablet, film coated
Oral
25 mg
Solution
10 mg/5ml
Tablet, coated
Oral
10 mg

### Prices

Unit description
Cost
Unit
Hydroxyzine Hcl 50 mg/ml
4.42USD
ml
Hydroxyzine 50 mg/ml vial
3.96USD
ml
Hydroxyzine 25 mg/ml vial
3.6USD
ml
Hydroxyzine hcl powder
2.75USD
g
Hydroxyzine pamoate powder
2.14USD
g
Vistaril 50 mg capsule
2.03USD
capsule
HydrOXYzine HCl 50 mg/ml vial
1.78USD
vial
Vistaril 25 mg capsule
1.71USD
capsule
Vistaril 100 mg capsule
1.7USD
capsule
Hydroxyzine hcl 50 mg tablet
1.19USD
tablet
Hydroxyzine hcl 10 mg tablet
0.72USD
tablet
Hydroxyzine hcl 25 mg tablet
0.7USD
tablet
HydrOXYzine Pamoate 100 mg capsule
0.67USD
capsule
Hydroxyzine pam 50 mg capsule
0.64USD
capsule
Hydroxyzine pam 100 mg capsule
0.63USD
capsule
Hydroxyzine pam 25 mg capsule
0.46USD
capsule
Vistaril 25 mg/5ml Suspension
0.45USD
ml
HydrOXYzine Pamoate 25 mg capsule
0.3USD
capsule
HydrOXYzine Pamoate 50 mg capsule
0.23USD
capsule
Apo-Hydroxyzine 50 mg Capsule
0.22USD
capsule
Novo-Hydroxyzin 50 mg Capsule
0.22USD
capsule
Apo-Hydroxyzine 25 mg Capsule
0.15USD
capsule
Novo-Hydroxyzin 25 mg Capsule
0.15USD
capsule
HydrOXYzine HCl 10 mg/5ml Syrup
0.13USD
ml
Apo-Hydroxyzine 10 mg Capsule
0.12USD
capsule
Novo-Hydroxyzin 10 mg Capsule
0.12USD
capsule
Atarax 2 mg/ml Syrup
0.06USD
ml
Pms-Hydroxyzine 2 mg/ml Syrup
0.04USD
ml
DrugBank does not sell nor buy drugs. Pricing information is supplied for informational purposes only.

### State

Solid

### Experimental Properties

Property
Value
Source
melting point (°C)
200C
Canadian Label

### Predicted Properties

Property
Value
Source
Water Solubility
0.0914 mg/mL
ALOGPS
logP
3.43
ALOGPS
logP
3.41
Chemaxon
logS
-3.6
ALOGPS
pKa (Strongest Acidic)
15.12
Chemaxon
pKa (Strongest Basic)
7.45
Chemaxon
Physiological Charge
1
Chemaxon
Hydrogen Acceptor Count
4
Chemaxon
Hydrogen Donor Count
1
Chemaxon
Polar Surface Area
35.94 Å
2
Chemaxon
Rotatable Bond Count
8
Chemaxon
Refractivity
107.07 m
3
·mol
-1
Chemaxon
Polarizability
41.99 Å
3
Chemaxon
Number of Rings
3
Chemaxon
Bioavailability
1
Chemaxon
Rule of Five
Yes
Chemaxon
Ghose Filter
Yes
Chemaxon
Veber's Rule
Yes
Chemaxon
MDDR-like Rule
Yes
Chemaxon

### Predicted ADMET Features

Property
Value
Probability
Human Intestinal Absorption
+
0.8623
Blood Brain Barrier
+
0.9516
Caco-2 permeable
-
0.5565
P-glycoprotein substrate
Substrate
0.7447
P-glycoprotein inhibitor I
Inhibitor
0.8563
P-glycoprotein inhibitor II
Inhibitor
0.6394
Renal organic cation transporter
Inhibitor
0.592
CYP450 2C9 substrate
Non-substrate
0.8352
CYP450 2D6 substrate
Non-substrate
0.9116
CYP450 3A4 substrate
Non-substrate
0.7193
CYP450 1A2 substrate
Non-inhibitor
0.9045
CYP450 2C9 inhibitor
Non-inhibitor
0.9111
CYP450 2D6 inhibitor
Inhibitor
0.8535
CYP450 2C19 inhibitor
Non-inhibitor
0.9026
CYP450 3A4 inhibitor
Non-inhibitor
0.9623
CYP450 inhibitory promiscuity
Low CYP Inhibitory Promiscuity
0.7615
Ames test
Non AMES toxic
0.7558
Carcinogenicity
Non-carcinogens
0.9102
Biodegradation
Not ready biodegradable
1.0
Rat acute toxicity
2.6612 LD50, mol/kg
Not applicable
hERG inhibition (predictor I)
Weak inhibitor
0.5929
hERG inhibition (predictor II)
Inhibitor
0.7898
ADMET data is predicted using
admetSAR
, a free tool for evaluating chemical ADMET properties. (
23092397
)

### Spectra

Spectrum
Spectrum Type
Splash Key
Predicted GC-MS Spectrum - GC-MS
Predicted GC-MS
splash10-0udj-4291000000-5750700bc5e75e581102
GC-MS Spectrum - EI-B
GC-MS
splash10-0udi-6491000000-95c46c16c2b29900f4d9
Mass Spectrum (Electron Ionization)
MS
splash10-0uxr-4591000000-d2e3424c44feae8a5d9c
MS/MS Spectrum - , positive
LC-MS/MS
splash10-0udi-0593000000-f20d2328497a3a80239b
Predicted MS/MS Spectrum - 10V, Positive (Annotated)
Predicted LC-MS/MS
splash10-004i-0009000000-ea8e9386af034db2f970
Predicted MS/MS Spectrum - 10V, Negative (Annotated)
Predicted LC-MS/MS
splash10-00di-4009000000-82a93759c53ebe3a9537
Predicted MS/MS Spectrum - 20V, Positive (Annotated)
Predicted LC-MS/MS
splash10-0zfr-0096000000-4e9aa5e0b6000400dc11
Predicted MS/MS Spectrum - 20V, Negative (Annotated)
Predicted LC-MS/MS
splash10-03kc-9028000000-ad990344a3859f84c00e
Predicted MS/MS Spectrum - 40V, Positive (Annotated)
Predicted LC-MS/MS
splash10-0ufr-5692000000-b6a27399e087ae28b29c
Predicted MS/MS Spectrum - 40V, Negative (Annotated)
Predicted LC-MS/MS
splash10-001i-9181000000-2983d1840355019c9e57
Predicted 1H NMR Spectrum
1D NMR
Not Applicable
Predicted 13C NMR Spectrum
1D NMR
Not Applicable

### Chromatographic Properties

Collision Cross Sections (CCS)
Adduct
CCS Value (Å
2
)
Source type
Source
[M-H]-
201.4104609
predicted
DarkChem Lite v0.1.0
[M-H]-
185.55614
predicted
DeepCCS 1.0 (2019)
[M+H]+
201.0609609
predicted
DarkChem Lite v0.1.0
[M+H]+
187.91415
predicted
DeepCCS 1.0 (2019)
[M+Na]+
201.2974609
predicted
DarkChem Lite v0.1.0
[M+Na]+
194.821
predicted
DeepCCS 1.0 (2019)

### Kind

Protein

### Organism

Humans

### Pharmacological action

Unknown

### Actions

Substrate

### General Function

Translocates drugs and phospholipids across the membrane (PubMed:2897240, PubMed:35970996, PubMed:8898203, PubMed:9038218, PubMed:35507548). Catalyzes the flop of phospholipids from the cytoplasmic to the exoplasmic leaflet of the apical membrane. Participates mainly to the flop of phosphatidylcholine, phosphatidylethanolamine, beta-D-glucosylceramides and sphingomyelins (PubMed:8898203). Energy-dependent efflux pump responsible for decreased drug accumulation in multidrug-resistant cells (PubMed:2897240, PubMed:35970996, PubMed:9038218)

### Specific Function

ABC-type xenobiotic transporter activity

### Gene Name

ABCB1

### Uniprot ID

P08183

### Uniprot Name

ATP-dependent translocase ABCB1

### Molecular Weight

141477.255 Da

`,
  "protestkit": `{
  "url": "https://drugs.tripsit.me/hydroxyzine",
  "experiencesUrl": "https://www.erowid.org/experiences/subs/exp_Hydroxyzine.shtml",
  "name": "Hydroxyzine",
  "aliases": [
    "atarax",
    "vistaril"
  ],
  "aliasesStr": "atarax,vistaril",
  "summary": "An antihistamine drug commonly prescribed for anxiety, itchiness, nausea, and insomnia. Hydroxyzine has also been used to potentiate the analgesia of opioids as well as diminishing the negative effects of opioids, such as itchiness.",
  "reagents": null,
  "classes": {
    "chemical": [],
    "psychoactive": [
      "Opioids"
    ]
  },
  "toxicity": null,
  "addictionPotential": null,
  "tolerance": null,
  "crossTolerances": null,
  "roas": [
    {
      "name": "Oral",
      "dosage": [
        {
          "name": "Common",
          "value": "25-100mg"
        }
      ],
      "duration": [
        {
          "name": "Onset",
          "value": "0.33 - 1.0 hours"
        },
        {
          "name": "Duration",
          "value": "3.0 - 5.0 hours"
        },
        {
          "name": "After effects",
          "value": "1.0 - 8.0 hours"
        }
      ]
    }
  ],
  "interactions": [
    {
      "name": "2C-T-x",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "2C-x",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "5-MeO-xxT",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "Alcohol",
      "status": "Dangerous"
    },
    {
      "name": "Amphetamines",
      "status": "Caution"
    },
    {
      "name": "Benzos",
      "status": "Dangerous"
    },
    {
      "name": "Caffeine",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "Cannabis",
      "status": "Low Risk & Synergy"
    },
    {
      "name": "Cocaine",
      "status": "Dangerous"
    },
    {
      "name": "DMT",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "DOx",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "DXM",
      "status": "Dangerous"
    },
    {
      "name": "GHB/GBL",
      "status": "Dangerous"
    },
    {
      "name": "Gabapentinoids",
      "status": "Dangerous"
    },
    {
      "name": "Ketamine",
      "status": "Dangerous"
    },
    {
      "name": "LSD",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "MAOIs",
      "status": "Caution"
    },
    {
      "name": "MDMA",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "MMC class",
      "status": "Unsafe"
    },
    {
      "name": "MXE",
      "status": "Dangerous"
    },
    {
      "name": "Mescaline",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "Mushrooms",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "NBOMes",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "Nitrous",
      "status": "Caution"
    },
    {
      "name": "PDA5",
      "status": "Unsafe"
    },
    {
      "name": "PVP class",
      "status": "Unsafe"
    },
    {
      "name": "Poppers",
      "status": "Dangerous"
    },
    {
      "name": "SSRIs",
      "status": "Low Risk & No Synergy"
    },
    {
      "name": "Tramadol",
      "status": "Dangerous"
    }
  ],
  "effects": null,
  "categorized_effects": {
    "Physical effects": [],
    "Mental effects": [],
    "Sensory effects": [],
    "Uncategorized effects": []
  }
}`,
  "tripsit-factsheets": `# Hydroxyzine
*Source: TripSit Factsheets (tripsit.me)*

## Summary

A antihistamine drug commonly prescribed for anxiety, itchiness, nausea, and insomnia. Hydroxyzine has also been used to potentiate the analgesia of opioids as well as diminishing negative effects of opioids, such as itchiness.

## Classification
- **Categories:** depressant, deliriant
- **Also known as:** vistaril, atarax

## Dosage

### Oral
- **Common:** 25-100mg

## Duration
- **Onset:** 20-60 minutes
- **Duration:** 3-5 hours
- **After Effects:** 1-8 hours

## External Links
- [experiences](https://www.erowid.org/experiences/subs/exp_Hydroxyzine.shtml)
`,
  "wikipedia": `# Hydroxyzine
*Source: https://en.wikipedia.org/wiki/Hydroxyzine*

Hydroxyzine, sold under the brand names Atarax and Vistaril among others, is an antihistamine medication. It is used in the treatment of itchiness, anxiety, insomnia, and nausea (including that due to motion sickness). It is used either by mouth or injection into a muscle.
Hydroxyzine works by blocking the effects of histamine. It is a first-generation antihistamine in the piperazine family of chemicals. Common side effects include sleepiness, headache, and dry mouth. Serious side effects may include QT prolongation. It is unclear if use during pregnancy or breastfeeding is safe.
It was first made by Union Chimique Belge in 1956 and was approved for sale by Pfizer in the United States later that year. In 2023, it was the 39th most commonly prescribed medication in the United States, with more than 15 million prescriptions.

## Medical uses

Hydroxyzine is used in the treatment of itchiness, anxiety, and nausea due to motion sickness.
A systematic review concluded that hydroxyzine outperforms placebo in treating generalized anxiety disorder. Insufficient data were available to compare the drug with benzodiazepines and buspirone.
Hydroxyzine can also be used for the treatment of allergic conditions, such as chronic urticaria, atopic or contact dermatoses, and histamine-mediated pruritus. These have also been confirmed in both recent and past studies to have no adverse effects on the liver, blood, nervous system, or urinary tract.
Use of hydroxyzine for premedication as a sedative has no effects on tropane alkaloids, such as atropine, but may, following general anesthesia, potentiate meperidine and barbiturates, and use in pre-anesthetic adjunctive therapy should be modified depending upon the state of the individual.
Doses of hydroxyzine hydrochloride used for sleep range from 25 to 100 mg. As with other antihistamine sleep aids, hydroxyzine is usually only prescribed for short term or "as-needed" use since tolerance to the central nervous system (CNS) effects of hydroxyzine can develop in as little as a few days. A major systematic review and network meta-analysis of medications for the treatment of insomnia published in 2022 found little evidence to inform the use of hydroxyzine for insomnia. A 2023 meta-review concludes that hydroxyzine is effective for inducing sleep onset but less effective for maintaining sleep for eight hours.

## Contraindications

Hydroxyzine is contraindicated for subcutaneous or intra-articular administration.
The administration of hydroxyzine in large amounts by ingestion or intramuscular administration during the onset of pregnancy can cause fetal abnormalities. When administered to pregnant rats, mice, and rabbits, hydroxyzine caused abnormalities such as hypogonadism with doses significantly above that of the human therapeutic range.
In humans, a significant dose has not yet been established in studies, and, by default, the US Food and Drug Administration (FDA) has introduced contraindication guidelines regarding hydroxyzine. Use by those at risk for or showing previous signs of hypersensitivity is also contraindicated.
Other contraindications include the administration of hydroxyzine alongside depressants and other compounds that affect the central nervous system; if necessary, it should only be administered concomitantly in small doses. If administered in small doses with other substances, as mentioned, then patients should refrain from using dangerous machinery, motor vehicles, or any other practice requiring absolute concentration, under safety laws.
Studies have also been conducted which show that long-term prescription of hydroxyzine can lead to tardive dyskinesia after years of use, but effects related to dyskinesia have also anecdotally been reported after periods of 7.5 months, such as continual head rolling, lip licking, and other forms of athetoid movement. In certain cases, elderly patients' previous interactions with phenothiazine derivatives or pre-existing neuroleptic treatment may have contributed to dyskinesia at the administration of hydroxyzine due to hypersensitivity caused by prolonged treatment, and therefore some contraindication is given for short-term administration of hydroxyzine to those with previous phenothiazine use.

## Side effects

Several reactions have been noted in manufacturer guidelines—deep sleep, incoordination, sedation, and dizziness have been reported in children and adults, as well as others such as hypotension, tinnitus, and headaches. Gastrointestinal effects have also been observed, as well as less serious effects such as dryness of the mouth and constipation caused by the mild antimuscarinic properties of hydroxyzine.
Central nervous system effects such as hallucinations or confusion have been observed in rare cases, attributed mostly to overdosage.  Such properties have been attributed to hydroxyzine in several cases, particularly in patients treated for neuropsychological disorders, as well as in cases where overdoses have been observed. While there are reports of hallucinogenic effects from use of hydroxyzine, several clinical data trials have not reported such side effects from the sole consumption of hydroxyzine, but rather, have described its overall calming effect described through the stimulation of areas within the reticular formation. The hallucinogenic or hypnotic properties have been described as being an additional effect from overall central nervous system suppression by other CNS agents, such as lithium or ethanol.
Hydroxyzine exhibits anxiolytic and sedative properties in many psychiatric patients. One study showed that patients reported very high levels of subjective sedation when first taking the drug, but that levels of reported sedation decreased markedly over 5–7 days, likely due to CNS receptor desensitization. Other studies have suggested that hydroxyzine acts as an acute hypnotic, reducing sleep onset latency and increasing sleep duration—also showing that some drowsiness did occur. This was observed more in female patients, who also had greater hypnotic responses. The use of sedating drugs alongside hydroxyzine can cause oversedation and confusion if administered at high doses—any form of hydroxyzine treatment alongside sedatives should be done under the supervision of a doctor.
Because of the potential for more severe side effects, this drug is on the list to avoid in the elderly.

## Pharmacology

### Pharmacodynamics

Hydroxyzine's predominant mechanism of action is as a potent and selective histamine H1 receptor inverse agonist. This action is responsible for its antihistamine and sedative effects. Unlike many other first-generation antihistamines, hydroxyzine has a lower affinity for the muscarinic acetylcholine receptors, and in accordance, has a lower risk of anticholinergic side effects. In addition to its antihistamine activity, hydroxyzine has also been shown to act more weakly as an antagonist of the serotonin 5-HT2A receptor, the dopamine D2 receptor, and the α1-adrenergic receptor. Similarly to the atypical antipsychotics, the comparably weak antiserotonergic effects of hydroxyzine likely underlie its usefulness as an anxiolytic. Other antihistamines without such properties have not been found to be effective in the treatment of anxiety.
Hydroxyzine crosses the blood–brain barrier easily and exerts effects in the central nervous system. A positron emission tomography (PET) study found that brain occupancy of the H1 receptor was 67.6% for a single 30 mg dose of hydroxyzine. In addition, subjective sleepiness correlated well with the brain H1 receptor occupancy. PET studies with antihistamines have found that brain H1 receptor occupancy of more than 50% is associated with a high prevalence of somnolence and cognitive decline, whereas brain H1 receptor occupancy of less than 20% is considered to be non-sedative.
Hydroxyzine also acts as a functional inhibitor of acid sphingomyelinase.

### Pharmacokinetics

Hydroxyzine can be administered orally or via intramuscular injection. In both cases it is rapidly absorbed and distributed. It is metabolized in the liver and the main metabolite (45%), cetirizine is formed through oxidation of the alcohol moiety to a carboxylic acid by alcohol dehydrogenase. Overall effects are observed within one hour of administration. 
Higher concentrations are found in the skin than in the plasma. Cetirizine, although less sedating, is non-dialyzable and possesses similar antihistamine properties. Metabolites identified include an N-dealkylated metabolite and an O-dealkylated 1/16 metabolite with a plasma half-life of 59 hours. These pathways are mediated principally by CYP3A4 and CYP3A5. The N-dealykylated metabolite, norchlorcyclizine, bears some structural similarities to trazodone, but it has not been established whether it is pharmacologically active.  In animals, hydroxyzine and its metabolites are excreted in feces primarily through biliary elimination. In rats, less than 2% of the drug is excreted unchanged.
The time to reach maximum concentration (Tmax) of hydroxyzine is about 2.0 hours in both adults and children and its elimination half-life is around 20.0 hours in adults (mean age 29.3 years) and 7.1 hours in children. Its elimination half-life is shorter in children compared to adults. In another study, the elimination half-life of hydroxyzine in elderly adults was 29.3 hours. One study found that the elimination half-life of hydroxyzine in adults was as short as 3 hours, but this may have just been due to methodological limitations. Although hydroxyzine has a long elimination half-life and acts, in-vivo, as an antihistamine for as long as 24 hours, the predominant CNS effects of hydroxyzine and other antihistamines with long half-lives seem to diminish after 8 hours.
Administration in geriatrics differs from the administration of hydroxyzine in younger patients; according to the FDA, there have not been significant studies made (2004), which include population groups over 65, which provide a distinction between elderly aged patients and other younger groups. Hydroxyzine should be administered carefully in the elderly with consideration given to possible reduced elimination.

## Chemistry

Hydroxyzine is a member of the diphenylmethylpiperazine class of antihistamines.
Hydroxyzine is supplied mainly as a dihydrochloride salt (hydroxyzine hydrochloride) but also to a lesser extent as an embonate salt (hydroxyzine pamoate). The molecular weights of hydroxyzine, hydroxyzine dihydrochloride, and hydroxyzine pamoate are 374.9 g/mol, 447.8 g/mol, and 763.3 g/mol, respectively. Due to their differences in molecular weight, 1 mg hydroxyzine dihydrochloride is equivalent to about 1.7 mg hydroxyzine pamoate.

### Analogues

Analogues of hydroxyzine include buclizine, cetirizine, cinnarizine, cyclizine, etodroxizine, meclizine, and pipoxizine among others.

## Society and culture

### Brand names

Hydroxyzine preparations require a doctor's prescription. The drug is available in two formulations, the pamoate and the dihydrochloride or hydrochloride salts. Vistaril, Equipose, Masmoran, and Paxistil are preparations of the pamoate salt, while Atarax, Alamon, Aterax, Durrax, Tran-Q, Orgatrax, Quiess, and Tranquizine are of the hydrochloride salt.
`,
};
