/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 */

import type { SubstanceArticle } from "../../schema";

/**
 * Create an empty SubstanceArticle with default values derived from the Zod schema.
 */
export function createEmptyArticle(): SubstanceArticle {
  return {
  id: null,
  title: "",
  priority: "normal",
  index_categories: [],
  identification: {
    common_name: "",
    substitutive_name: "",
    iupac_name: "",
    alternative_names: [],
    smiles: "",
    inchi_key: "",
    cas_number: "",
    molecular_formula: "",
    molecular_weight: "",
    skeletal_structure_image: "",
    botanical_name: ""
  },
  classification: {
    psychoactive_class: [],
    chemical_class: []
  },
  summary: "",
  dosage: {
    routes: [],
    plateau_dosing: null
  },
  duration: {
    routes: []
  },
  subjective_effects: {
    notes: {
      overview: "",
      sensory: "",
      cognitive: "",
      physical: ""
    },
    sensory: {
      visual: {
        note: "",
        subcategories: {}
      },
      auditory: {
        note: "",
        subcategories: {}
      },
      tactile: {
        note: "",
        subcategories: {}
      },
      olfactory: {
        note: "",
        subcategories: {}
      },
      gustatory: {
        note: "",
        subcategories: {}
      },
      multisensory: {
        note: "",
        subcategories: {}
      }
    },
    cognitive: {},
    physical: {}
  },
  comparisons: [],
  pharmacology: {
    pharmacodynamics: "",
    binding_sites: [],
    pharmacokinetics: "",
    metabolites: [],
    route_bioavailability: {},
    route_half_life: {},
    route_half_life_notes: {},
    route_bioavailability_notes: {}
  },
  interactions: {
    dangerous: [],
    unsafe: [],
    caution: []
  },
  reagent_testing: {},
  tolerance: {
    full_tolerance: "",
    half_tolerance: "",
    baseline_tolerance: "",
    cross_tolerance: []
  },
  harm_potential: {
    addiction: {
      psychological: {
        level: null,
        description: ""
      },
      physical_dependence: {
        level: null,
        description: ""
      }
    },
    toxicity: {
      lethal_dosage: {
        ld50: [],
        notes: ""
      },
      organ_toxicity: [],
      carcinogenicity: {
        level: null,
        evidence: null,
        description: ""
      },
      antibiotic_function: {
        level: null,
        description: ""
      },
      other: ""
    },
    psychosis: {
      level: null,
      description: ""
    },
    seizure: {
      level: null,
      description: ""
    }
  },
  history_culture: {
    content: "",
    sections: []
  },
  legality: {
    international: [],
    countries: {},
    usStates: {}
  },
  editorial_review: {
    status: "needed",
    notes: ""
  },
  section_gaps: {
    neighbours: [],
    sections: {}
  },
  references: [],
  source_citations: [],
  citations: []
};
}
