/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: npm run generate:schema
 * Source: src/schema/substance.schema.ts
 *
 * This barrel composes generated field-registry shards by domain.
 * Manual overrides (labels, sections, transformers) are defined in fieldOverrides.ts
 */

import { metaGeneratedFieldRegistry } from "./fieldRegistry.generated/meta";
import { identificationGeneratedFieldRegistry } from "./fieldRegistry.generated/identification";
import { classificationGeneratedFieldRegistry } from "./fieldRegistry.generated/classification";
import { dosageGeneratedFieldRegistry } from "./fieldRegistry.generated/dosage";
import { durationGeneratedFieldRegistry } from "./fieldRegistry.generated/duration";
import { subjective_effectsGeneratedFieldRegistry } from "./fieldRegistry.generated/subjective_effects";
import { pharmacologyGeneratedFieldRegistry } from "./fieldRegistry.generated/pharmacology";
import { interactionsGeneratedFieldRegistry } from "./fieldRegistry.generated/interactions";
import { toleranceGeneratedFieldRegistry } from "./fieldRegistry.generated/tolerance";
import { harm_potentialGeneratedFieldRegistry } from "./fieldRegistry.generated/harm_potential";
import { citationsGeneratedFieldRegistry } from "./fieldRegistry.generated/citations";

export interface GeneratedFieldMeta {
  path: string;
  type: string;
  default: unknown;
  isNullable: boolean;
}

export const GENERATED_FIELD_REGISTRY: Record<string, GeneratedFieldMeta> = {
  ...metaGeneratedFieldRegistry,
  ...identificationGeneratedFieldRegistry,
  ...classificationGeneratedFieldRegistry,
  ...dosageGeneratedFieldRegistry,
  ...durationGeneratedFieldRegistry,
  ...subjective_effectsGeneratedFieldRegistry,
  ...pharmacologyGeneratedFieldRegistry,
  ...interactionsGeneratedFieldRegistry,
  ...toleranceGeneratedFieldRegistry,
  ...harm_potentialGeneratedFieldRegistry,
  ...citationsGeneratedFieldRegistry,
};

/**
 * List of all field paths in the schema
 */
export const FIELD_PATHS = Object.keys(GENERATED_FIELD_REGISTRY);

export type FieldPath = (typeof FIELD_PATHS)[number];
